#!/usr/bin/env python3

"""
---
Generated by Claude.ai Sonnet 5 (Medium effort)
---

Run a prompt against a locally running OpenCode 2 server (HttpApi v2), with a
specific agent, skill, and provider/model — and get live visibility into what
the agent is doing: thinking (reasoning), tool calls, skill use, sub-agent
invocations, and token / context-window usage.

Requires OpenCode 2 running locally, e.g.:

    opencode2 serve --port 4096

Docs: https://opencode.ai/v2/docs/api

CLI usage:
    python opencode_run.py \
        --prompt "Refactor this function for clarity" \
        --agent build \
        --skill code-review \
        --provider anthropic \
        --model claude-sonnet-5 \
        --directory /path/to/your/project

Add --quiet to suppress live output and just print the final answer.
Add --log-file PATH to send live output to a file instead of stdout.

Library usage:
    from opencode_run import chat, Event
    import argparse

    def on_event(event: Event) -> None:
        ...  # forward to LangSmith, structured logging, whatever you like

    args = argparse.Namespace(base_url=..., agent="build", prompt="...", ...)
    reply = chat(args, on_event=on_event)

--- Architecture ---

Nothing in this module prints directly. Everything that happens during a
run — thinking deltas, tool-call transitions, skill activation, sub-agent
discovery, token/cost/context updates, the final answer — is emitted as an
`Event` to a single `on_event` callback. This keeps the client itself
un-opinionated about where output goes; `make_stream_listener()` and
`file_listener()` are just two simple reference listeners (stdout / file)
built on top of that same callback contract. Anything else — LangSmith,
OpenTelemetry, structured JSON logging — is just a different `on_event`
implementation, written outside this file.

Each Event carries a `key` (a unique id for the "span" it belongs to,
e.g. a specific tool call or thinking block) and a `parent_key` (the key
of the span it's logically nested under). Sub-agent sessions inherit the
key of the "task" tool call that spawned them as their `parent_key`, so a
listener can reconstruct proper nesting (e.g. LangSmith parent/child runs)
without relying on the numeric `depth` field, which only tells you how
deep something is, not which sibling span it belongs under.

--- Design notes / known assumptions ---

The v2 HttpApi is marked "experimental" and its SSE event payload shape
(GET /api/event) isn't documented beyond the outer envelope
{id, event, data}. Rather than depend on parsing that payload precisely,
this script uses the event stream only as a low-latency "something
changed, go re-sync" signal (falling back to polling on a fixed interval
regardless, so it degrades gracefully if SSE payload parsing ever fails
or the stream drops). Rendering is always driven by re-reading
GET /api/session/{id} and GET /api/session/{id}/message, so what you see
is always ground truth from the API, just possibly ~1 poll-interval late
if SSE didn't wake us early.

Sub-agent discovery: the model invokes sub-agents via a "task" tool.
There is no documented field linking a task-tool call directly to the
child session it spawns, so this script infers it heuristically: after a
"task" tool call appears, it lists all sessions and claims the newest
not-yet-claimed session whose parentID matches the current session. This
works well for the common case of sequential sub-agent calls; if an agent
fires many sub-agents in tight parallel, attribution to the *correct*
task call may be approximate (though every child session is still found
and rendered).
"""

import argparse
import contextlib
import os
import queue
import sys
import threading
import time
from datetime import datetime
from dataclasses import dataclass, field
from typing import Any, Callable, Optional

import requests


DEFAULT_BASE_URL = "http://localhost:4096"
POLL_FALLBACK_INTERVAL = 1.5  # seconds; used when no SSE event wakes us up
TEXT_PREVIEW_CHARS = 4000     # cap how much of a single text/reasoning delta we emit at once


# --------------------------------------------------------------------------
# HTTP client
# --------------------------------------------------------------------------

class ProviderUnavailableError(RuntimeError):
    """Raised specifically when the model provider itself could not be
    reached (HTTP 503, _tag "ServiceUnavailableError", message matching a
    provider-request failure). See note on ServiceUnavailableGeneric below —
    this _tag is a generic wrapper server-side, so this is only raised when
    the message content actually indicates a provider-connectivity problem.
    """

    def __init__(self, service: str | None, detail: str):
        self.service = service
        self.detail = detail
        super().__init__(
            f"The model provider could not be reached (service: {service or 'unknown'}). "
            f"OpenCode sent the request successfully, but the provider itself did not "
            f"respond. This is a provider/network issue, not a bug in this script — check "
            f"that the provider configured for this session's model is reachable and "
            f"correctly configured. Raw detail: {detail}"
        )


class AgentNotFoundError(RuntimeError):
    """Raised when a requested agent isn't found by GET /api/agent for the
    given directory. Mirrors SkillNotFoundError: Agent.Info has both an
    `id` and a `name`, so this is raised with the real available list
    rather than a bare error, to make an id/name mismatch obvious."""

    def __init__(self, requested: str, directory: str, available: list[dict]):
        self.requested = requested
        self.directory = directory
        self.available = available
        listing = ", ".join(f"{a.get('name')!r} (id={a.get('id')!r})" for a in available) or "(none found)"
        super().__init__(
            f"Agent {requested!r} not found for directory {directory!r}. "
            f"Available agents here: {listing}"
        )


class ServiceUnavailableGeneric(RuntimeError):
    """Raised for a 503 ServiceUnavailableError whose message doesn't match
    a recognized specific case (provider failure, agent-not-found, etc.).
    IMPORTANT: this _tag is a generic wrapper OpenCode uses for multiple
    unrelated 'operation can't complete right now' conditions server-side
    (confirmed by seeing it used for both provider failures AND agent
    resolution failures) — there's no structured discriminator beyond the
    message text, so this is the honest fallback rather than guessing."""

    def __init__(self, service: str | None, detail: str):
        self.service = service
        self.detail = detail
        super().__init__(f"Service unavailable (service: {service or 'unknown'}): {detail}")


class SkillNotFoundError(RuntimeError):
    """Raised when a requested skill isn't found by GET /api/skill for the
    given directory. Skill.Info has both an `id` and a `name` field, and
    they're not guaranteed to be the same string — this is raised with the
    actual list of what's available so it's obvious whether the requested
    skill just needs the right identifier, or genuinely isn't registered
    for that directory."""

    def __init__(self, requested: str, directory: str, available: list[dict]):
        self.requested = requested
        self.directory = directory
        self.available = available
        listing = ", ".join(f"{s.get('name')!r} (id={s.get('id')!r})" for s in available) or "(none found)"
        super().__init__(
            f"Skill {requested!r} not found for directory {directory!r}. "
            f"Available skills here: {listing}"
        )


class OpenCodeClient:
    def __init__(
        self,
        base_url: str = DEFAULT_BASE_URL,
        username: str | None = None,
        password: str | None = None,
    ):
        self.base_url = base_url.rstrip("/")
        self.session = requests.Session()
        # OpenCode 2 secures `opencode2 serve` with HTTP Basic Auth. Unlike v1
        # (unauthenticated unless OPENCODE_SERVER_PASSWORD is set), v2 generates
        # a random password if none is configured, and prints it at server
        # startup. Environment variables mirror what `opencode2` itself reads:
        # OPENCODE_PASSWORD / OPENCODE_SERVER_PASSWORD for the password, and
        # OPENCODE_SERVER_USERNAME for the username (defaults to "opencode").
        password = password or os.environ.get("OPENCODE_PASSWORD") or os.environ.get("OPENCODE_SERVER_PASSWORD")
        username = username or os.environ.get("OPENCODE_SERVER_USERNAME") or "opencode"
        if password:
            self.session.auth = requests.auth.HTTPBasicAuth(username, password)

    def _url(self, path: str) -> str:
        return f"{self.base_url}{path}"

    def _check_auth_error(self, resp: requests.Response) -> None:
        if resp.status_code == 401:
            raise RuntimeError(
                "OpenCode server rejected the request (401 Unauthorized). "
                "The server requires HTTP Basic Auth — pass --password (and --username "
                "if you changed it), or set OPENCODE_PASSWORD / OPENCODE_SERVER_PASSWORD. "
                "opencode2 prints the auto-generated password to its own stdout/log at "
                "startup if you didn't set one explicitly."
            )

    def _check_provider_error(self, resp: requests.Response) -> None:
        """The v2 API's _tag "ServiceUnavailableError" is a generic wrapper
        used for multiple, unrelated 'operation can't complete right now'
        conditions server-side — confirmed by seeing it used both for an
        actual upstream provider failure AND for agent resolution failure,
        with no structured field distinguishing which. So: pattern-match the
        message for known specific cases and raise the right exception type;
        fall back to the honest generic ServiceUnavailableGeneric otherwise
        rather than mislabeling everything as a provider problem."""
        if resp.status_code != 503:
            return
        try:
            body = resp.json()
        except ValueError:
            return
        if body.get("_tag") != "ServiceUnavailableError":
            return
        message = body.get("message", "")
        service = body.get("service")
        lower = message.lower()
        if "agent not found" in lower:
            # message is typically "agent not found: <id>"
            agent_id = message.split(":", 1)[-1].strip() if ":" in message else message
            raise AgentNotFoundError(requested=agent_id, directory="(unknown)", available=[])
        if "provider request failed" in lower or "requestexecutor" in lower:
            raise ProviderUnavailableError(service=service, detail=message)
        raise ServiceUnavailableGeneric(service=service, detail=message)

    def _raise_for_status(self, resp: requests.Response) -> None:
        """Like resp.raise_for_status(), but includes the response body — the
        v2 API is 'experimental' and its validation error bodies (e.g. which
        field was rejected) are the fastest way to diagnose a 400, rather than
        requests' default one-line summary."""
        if resp.status_code >= 400:
            raise requests.exceptions.HTTPError(
                f"{resp.status_code} error for {resp.request.method} {resp.url}\n"
                f"Response body: {resp.text[:2000]}",
                response=resp,
            )

    # -- health / misc -------------------------------------------------

    def health(self) -> dict:
        resp = self.session.get(self._url("/api/health"))
        self._check_auth_error(resp)
        self._raise_for_status(resp)
        return resp.json()

    # -- session lifecycle ----------------------------------------------

    def create_session(
        self,
        directory: str,
        agent: str | None = None,
        title: str | None = None,
        provider_id: str | None = None,
        model_id: str | None = None,
        variant: str | None = None,
    ) -> str:
        body: dict[str, Any] = {"location": {"directory": directory}}
        if agent:
            body["agent"] = agent
        if title:
            body["title"] = title
        if provider_id or model_id:
            if not (provider_id and model_id):
                raise ValueError("Both provider and model must be given together")
            model_ref = {"id": model_id, "providerID": provider_id}
            if variant:
                model_ref["variant"] = variant
            body["model"] = model_ref

        resp = self.session.post(self._url("/api/session"), json=body)
        self._check_auth_error(resp)
        self._raise_for_status(resp)
        return resp.json()["data"]["id"]

    def get_session(self, session_id: str) -> dict:
        resp = self.session.get(self._url(f"/api/session/{session_id}"))
        self._check_auth_error(resp)
        self._raise_for_status(resp)
        return resp.json()["data"]

    def list_sessions(self) -> list[dict]:
        resp = self.session.get(self._url("/api/session"))
        self._check_auth_error(resp)
        self._raise_for_status(resp)
        return resp.json()["data"]

    def switch_agent(self, session_id: str, agent: str) -> None:
        resp = self.session.post(
            self._url(f"/api/session/{session_id}/agent"), json={"agent": agent}
        )
        self._check_auth_error(resp)
        self._raise_for_status(resp)

    def list_agents(self, directory: str | None = None) -> list[dict]:
        """GET /api/agent — returns Agent.Info[] scoped to `directory` (same
        deepObject query style as /api/skill: location[directory]=...)."""
        params = {}
        if directory:
            params["location[directory]"] = directory
        resp = self.session.get(self._url("/api/agent"), params=params)
        self._check_auth_error(resp)
        self._raise_for_status(resp)
        return resp.json()["data"]

    def resolve_agent(self, directory: str, agent_query: str) -> str:
        """Looks up `agent_query` (as typed by the user, e.g. matching what
        the TUI displays) against the real agent list for `directory` and
        returns the identifier the API actually expects. Agent.Info has
        separate `id` and `name` fields that aren't guaranteed to match —
        this is exactly the failure mode that surfaced as a misleading
        ProviderUnavailableError before _check_provider_error learned to
        disambiguate 'agent not found' messages. Raises AgentNotFoundError
        (with the real available list) if nothing matches."""
        agents = self.list_agents(directory=directory)
        for a in agents:
            if a.get("id") == agent_query:
                return a["id"]
        for a in agents:
            if (a.get("name") or "").lower() == agent_query.lower():
                return a["id"]
        for a in agents:
            if (a.get("id") or "").lower() == agent_query.lower():
                return a["id"]
        raise AgentNotFoundError(requested=agent_query, directory=directory, available=agents)

    def switch_model(self, session_id: str, provider_id: str, model_id: str, variant: str | None = None) -> None:
        model_ref = {"id": model_id, "providerID": provider_id}
        if variant:
            model_ref["variant"] = variant
        resp = self.session.post(
            self._url(f"/api/session/{session_id}/model"), json={"model": model_ref}
        )
        self._check_auth_error(resp)
        self._raise_for_status(resp)

    def list_skills(self, directory: str | None = None) -> list[dict]:
        """GET /api/skill — returns Skill.Info[] scoped to `directory` (query
        param uses OpenAPI 'deepObject' style: location[directory]=...)."""
        params = {}
        if directory:
            params["location[directory]"] = directory
        resp = self.session.get(self._url("/api/skill"), params=params)
        self._check_auth_error(resp)
        self._raise_for_status(resp)
        return resp.json()["data"]

    def resolve_skill(self, directory: str, skill_query: str) -> str:
        """Looks up `skill_query` against the real skill list for `directory`
        and returns the identifier `activate_skill` should actually send.
        Skill.Info has separate `id` and `name` fields (e.g. a TUI might
        display `name` while the activation endpoint expects `id`, or vice
        versa) — this matches either, case-insensitively, before giving up.
        Raises SkillNotFoundError (with the real available list) if nothing
        matches, rather than a bare 404."""
        skills = self.list_skills(directory=directory)
        for s in skills:
            if s.get("id") == skill_query:
                return s["id"]
        for s in skills:
            if (s.get("name") or "").lower() == skill_query.lower():
                return s["id"]
        for s in skills:
            if (s.get("id") or "").lower() == skill_query.lower():
                return s["id"]
        raise SkillNotFoundError(requested=skill_query, directory=directory, available=skills)

    def activate_skill(self, session_id: str, skill: str, resume: bool = False) -> None:
        resp = self.session.post(
            self._url(f"/api/session/{session_id}/skill"),
            json={"skill": skill, "resume": resume},
        )
        self._check_auth_error(resp)
        if resp.status_code == 404:
            try:
                body = resp.json()
            except ValueError:
                body = {}
            if body.get("_tag") == "SkillNotFoundError":
                # Caller should normally have gone through resolve_skill() first,
                # so this is a fallback in case that was skipped or the skill
                # disappeared between resolution and activation.
                raise SkillNotFoundError(requested=body.get("skill", skill), directory="(unknown)", available=[])
        self._raise_for_status(resp)

    def send_prompt(self, session_id: str, text: str, resume: bool = True) -> dict:
        # Confirmed via the live OpenAPI doc (both the request schema AND,
        # critically, this endpoint's own summary text): "Durably admit one
        # session input and schedule agent-loop execution unless resume is
        # false." So `resume` genuinely controls whether the agent loop
        # actually runs — an earlier version of this client omitted it
        # entirely as "unconfirmed," which is the most likely reason /prompt
        # appeared to only stage a message without ever generating a reply.
        # Sending resume=True explicitly is what actually triggers the full
        # agent loop (tools, skills, sub-agents) — this is the real "run a
        # turn" path; see generate() below for the much more limited
        # alternative.
        body: dict[str, Any] = {"text": text, "resume": resume}
        resp = self.session.post(
            self._url(f"/api/session/{session_id}/prompt"),
            json=body,
        )
        self._check_auth_error(resp)
        self._check_provider_error(resp)
        self._raise_for_status(resp)
        return resp.json()["data"]

    def generate(self, session_id: str, prompt: str, timeout: float = 600.0) -> str:
        """POST /api/session/{id}/generate. NOTE: confirmed via the OpenAPI
        doc's own description — "Generate transient text from the current
        session context WITHOUT MUTATING SESSION HISTORY" — this is a
        lightweight, non-agentic single completion. It does NOT run tools,
        does NOT invoke skills/sub-agents, does NOT persist a message, and
        does NOT spend recorded tokens. It's useful for a one-off text
        completion over existing context, but NOT for agentic tasks that
        need to actually act (write files, call tools, etc.) — use
        send_prompt(resume=True) + wait() for that instead."""
        resp = self.session.post(
            self._url(f"/api/session/{session_id}/generate"),
            json={"prompt": prompt},
            timeout=timeout + 30,
        )
        self._check_auth_error(resp)
        self._check_provider_error(resp)
        self._raise_for_status(resp)
        return resp.json()["data"]["text"]

    def wait(self, session_id: str, timeout: float = 600.0) -> None:
        """Blocks (server-side) until the session's agent loop goes idle."""
        resp = self.session.post(
            self._url(f"/api/session/{session_id}/wait"),
            timeout=timeout + 30,
        )
        if resp.status_code not in (200, 204):
            self._check_auth_error(resp)
            self._check_provider_error(resp)
            self._raise_for_status(resp)

    def get_messages(self, session_id: str, order: str = "asc", limit: int = 200) -> list[dict]:
        # NOTE: 200 is the server's actual max (confirmed via a live 400:
        # "Expected a value less than or equal to 200, got 500 at [\"limit\"]").
        # This was silently breaking every single poll — caught by the
        # consecutive-poll-failure surfacing, since it's a real HTTPError,
        # not a transient network blip, so it fired the same "lost the
        # ability to poll" alert every run once that safeguard was added.
        resp = self.session.get(
            self._url(f"/api/session/{session_id}/message"),
            params={"order": order, "limit": limit},
        )
        self._check_auth_error(resp)
        self._raise_for_status(resp)
        return resp.json()["data"]

    def list_models(self) -> list[dict]:
        resp = self.session.get(self._url("/api/model"))
        self._check_auth_error(resp)
        self._raise_for_status(resp)
        return resp.json()["data"]

    def event_stream(self):
        """Yields (event_name, raw_data_str) tuples from GET /api/event (SSE).
        Never raises out of the generator on transient errors — the caller
        (SSEWaker) treats any exception as "reconnect after a short pause".
        Note: this is OpenCode's own server-sent-event stream, unrelated to
        the `Event` objects this module emits to `on_event` — see SSEWaker.
        """
        with self.session.get(self._url("/api/event"), stream=True, timeout=None) as resp:
            self._check_auth_error(resp)
            self._raise_for_status(resp)
            event_name = None
            data_lines: list[str] = []
            for raw_line in resp.iter_lines(decode_unicode=True):
                if raw_line is None:
                    continue
                line = raw_line
                if line == "":
                    if data_lines:
                        yield (event_name, "\n".join(data_lines))
                    event_name, data_lines = None, []
                    continue
                if line.startswith("event:"):
                    event_name = line[len("event:"):].strip()
                elif line.startswith("data:"):
                    data_lines.append(line[len("data:"):].strip())
                # ignore "id:" and comment lines (":") — not needed here


# --------------------------------------------------------------------------
# Model catalog (for context-window sizing)
# --------------------------------------------------------------------------

class ModelCatalog:
    def __init__(self, client: OpenCodeClient):
        self.client = client
        self._by_provider_model: dict[tuple[str, str], int] = {}
        self._by_id: dict[str, int] = {}
        self._loaded = False

    def _load(self) -> None:
        try:
            for m in self.client.list_models():
                ctx = (m.get("limit") or {}).get("context")
                if not ctx:
                    continue
                self._by_provider_model[(m["providerID"], m["modelID"])] = ctx
                self._by_id[m["id"]] = ctx
        except requests.exceptions.RequestException:
            pass  # context-window display is best-effort
        self._loaded = True

    def context_limit(self, model_ref: dict | None) -> Optional[int]:
        if not model_ref:
            return None
        if not self._loaded:
            self._load()
        key = (model_ref.get("providerID"), model_ref.get("id"))
        if key in self._by_provider_model:
            return self._by_provider_model[key]
        return self._by_id.get(model_ref.get("id"))


# --------------------------------------------------------------------------
# Background "wake me on change" signal via SSE, with polling fallback
# --------------------------------------------------------------------------

class SSEWaker:
    def __init__(self, client: OpenCodeClient):
        self.client = client
        self._q: "queue.Queue[None]" = queue.Queue(maxsize=1)
        self._stop = threading.Event()
        self._thread = threading.Thread(target=self._run, daemon=True)

    def start(self) -> None:
        self._thread.start()

    def stop(self) -> None:
        self._stop.set()

    def _run(self) -> None:
        while not self._stop.is_set():
            try:
                for _event_name, _data in self.client.event_stream():
                    if self._stop.is_set():
                        return
                    self._nudge()
            except requests.exceptions.RequestException:
                pass
            if not self._stop.is_set():
                time.sleep(1.0)  # brief pause before reconnecting

    def _nudge(self) -> None:
        try:
            self._q.put_nowait(None)
        except queue.Full:
            pass

    def wait(self, timeout: float) -> bool:
        """Blocks until either an SSE event arrives or timeout elapses.
        Returns True if woken by an event, False on timeout (fallback poll)."""
        try:
            self._q.get(timeout=timeout)
            return True
        except queue.Empty:
            return False


# --------------------------------------------------------------------------
# Events: the single channel everything is reported through
# --------------------------------------------------------------------------

# EventKey uniquely identifies the "span" an Event belongs to, e.g. a
# specific tool call, a specific thinking block, or a session-level status
# line. Reusing the same key across multiple Events (e.g. a tool going
# running -> completed, or a reasoning block growing) means "these are the
# same span, at different points in time" — that's what a listener should
# use to match a start to its end, not depth or arrival order.
EventKey = tuple


@dataclass
class Event:
    ts: float
    session_id: str
    depth: int
    key: EventKey
    parent_key: Optional[EventKey]   # key of the enclosing span (e.g. the "task" tool call
                                      # that spawned this session); None at the root
    kind: str                        # "lifecycle" | "status" | "text" | "reasoning" | "tool" |
                                      # "skill" | "agent-switched" | "model-switched" | "user" |
                                      # "compaction" | "subagent-spawned" | "final"
    name: Optional[str] = None       # tool/skill/agent name, where applicable
    status: Optional[str] = None     # e.g. "running" | "completed" | "error" | "delta" | None
    data: dict = field(default_factory=dict)


Listener = Callable[[Event], None]


def null_listener(_event: Event) -> None:
    """A listener that discards everything. Used for --quiet."""


# -- reference listener #1: human-readable indented tree, to stdout or a file --

_ICONS = {
    "lifecycle": "\u25B6",            # ▶
    "status": "\U0001F4CA",           # 📊
    "text": "\U0001F4AC",             # 💬
    "reasoning": "\U0001F9E0",        # 🧠
    "tool": "\U0001F527",             # 🔧 (overridden to 🤖/✅/❌ below)
    "skill": "\U0001F4CE",            # 📎
    "agent-switched": "\U0001F501",   # 🔁
    "model-switched": "\U0001F501",   # 🔁
    "user": "\U0001F464",             # 👤
    "compaction": "\U0001F5DC",       # 🗜
    "subagent-spawned": "\U0001F440", # 👀
    "final": "\U0001F3C1",            # 🏁
    "error": "\U0001F6A8",            # 🚨
    "unknown": "\u2753",              # ❓
}


def _format_event(event: Event) -> Optional[str]:
    """Renders an Event as a human-readable line, or None to skip it."""
    d = event.data

    if event.kind == "status":
        return (
            f"[{d.get('label')}] tokens: {d.get('tokens_str')} | "
            f"context: {d.get('context_used')}/{d.get('context_limit') or '?'} "
            f"({d.get('context_pct') or '?'}) | cost: ${d.get('cost') or 0:.4f}"
        )
    if event.kind in ("text", "reasoning"):
        return d.get("delta", "")
    if event.kind == "tool":
        if event.status in ("streaming", "running"):
            return f"tool: {event.name} ({event.status}) input={d.get('input_preview')}"
        if event.status == "completed":
            return f"tool: {event.name} completed -> {d.get('output_preview')}"
        if event.status == "error":
            return f"tool: {event.name} error -> {d.get('error')}"
        return None
    if event.kind == "skill":
        return f"skill activated: {event.name}"
    if event.kind == "agent-switched":
        return f"agent switched -> {event.name}"
    if event.kind == "model-switched":
        return f"model switched -> {d.get('providerID')}/{d.get('id')}"
    if event.kind == "user":
        return f"user: {d.get('preview')}"
    if event.kind == "compaction":
        return f"compaction {event.status} ({d.get('reason')})"
    if event.kind == "subagent-spawned":
        return f"-> spawned child session {d.get('child_session_id')} ({event.name})"
    if event.kind == "lifecycle":
        return d.get("message", event.name)
    if event.kind == "error":
        return d.get("message", str(d.get("error")))
    if event.kind == "unknown":
        return d.get("message", f"unrecognized: {event.name}")
    if event.kind == "final":
        return f"final reply ({len(d.get('reply', ''))} chars):\n{d.get('reply', '')}"
    return None


def make_stream_listener(log: Callable[[str], None] = print) -> Listener:
    """Reference listener: formats Events as indented, icon-prefixed lines
    and hands each line to `log` (defaults to `print`, i.e. stdout).

    Swap `log` for anything that takes a string — a wrapped file handle, a
    `logging.Logger.info`, an app-specific `log()` function, etc. This
    function is just a convenience; it isn't required, `on_event` accepts
    any `Callable[[Event], None]`.
    """
    def listener(event: Event) -> None:
        text = _format_event(event)
        if text is None:
            return
        prefix = "\u2502  " * event.depth  # "│  " per depth level
        time = datetime.now().strftime("(%H:%M)")
        icon = _ICONS.get(event.kind, "\u2022")
        if event.kind == "tool":
            if event.name == "task":
                icon = "\U0001F916"  # 🤖
            elif event.status == "completed":
                icon = "\u2705"
            elif event.status == "error":
                icon = "\u274C"
        for i, line in enumerate(text.splitlines() or [""]):
            marker = icon if i == 0 else "  "
            log(f"{prefix}{time} {marker} {line}")

    return listener


@contextlib.contextmanager
def file_listener(path: str, mode: str = "a"):
    """Reference listener: same rendering as make_stream_listener(), written
    to a file instead of stdout. Use as a context manager:

        with file_listener("run.log") as on_event:
            chat(args, on_event=on_event)
    """
    f = open(path, mode, encoding="utf-8")

    def log(line: str) -> None:
        f.write(line + "\n")
        f.flush()

    try:
        yield make_stream_listener(log)
    finally:
        f.close()


def fmt_tokens(tokens: dict) -> str:
    cache = tokens.get("cache", {}) or {}
    return (
        f"in={tokens.get('input', 0)} out={tokens.get('output', 0)} "
        f"reasoning={tokens.get('reasoning', 0)} "
        f"cache(read={cache.get('read', 0)},write={cache.get('write', 0)})"
    )


# --------------------------------------------------------------------------
# Monitor: polls (SSE-nudged) session + message state and emits Events
# --------------------------------------------------------------------------

@dataclass
class SessionNode:
    session_id: str
    parent_id: Optional[str]
    depth: int
    label: str
    spawn_key: Optional[EventKey] = None  # key of the "task" tool call that spawned this
                                           # session; every Event this node emits nests
                                           # under it. None for the root session.
    known_message_ids: set = field(default_factory=set)
    part_state: dict = field(default_factory=dict)   # (message_id, idx) -> {"status": ..., "len": ...}
    spawned_children: set = field(default_factory=set)   # tool part keys already resolved to a child session
    claimed_child_ids: set = field(default_factory=set)
    last_status_line: Optional[str] = None
    model_ref: Optional[dict] = None
    consecutive_poll_failures: int = 0
    poll_failure_reported: bool = False


class Monitor:
    """Polls (SSE-nudged) session + message state and emits Events describing
    everything that happens, across the root session and any sub-agent
    sessions it spawns."""

    def __init__(self, client: OpenCodeClient, catalog: ModelCatalog, on_event: Listener):
        self.client = client
        self.catalog = catalog
        self.on_event = on_event
        self.nodes: dict[str, SessionNode] = {}

    def run(self, root_session_id: str, root_agent_label: str, run_fn: Callable[[], str]) -> str:
        """Starts `run_fn` (a blocking call that runs the turn and returns the
        final reply text, e.g. client.generate(...)) in a background thread,
        and renders the live tree via SSE-nudged polling until it completes."""
        self.nodes[root_session_id] = SessionNode(
            session_id=root_session_id, parent_id=None, depth=0, label=root_agent_label
        )

        waker = SSEWaker(self.client)
        waker.start()

        run_result: list[str] = []
        run_error: list[Exception] = []
        run_done = threading.Event()

        def _run_target():
            try:
                run_result.append(run_fn())
            except Exception as e:  # noqa: BLE001
                run_error.append(e)
                if isinstance(e, ProviderUnavailableError):
                    msg = f"model provider unreachable (service: {e.service}): {e.detail}"
                elif isinstance(e, AgentNotFoundError):
                    msg = str(e)
                elif isinstance(e, ServiceUnavailableGeneric):
                    msg = f"service unavailable (service: {e.service}): {e.detail}"
                else:
                    msg = f"generation failed: {e}"
                self._emit(
                    self.nodes[root_session_id], key=(root_session_id, "run-error"),
                    kind="error", data={"message": msg},
                )
            finally:
                run_done.set()

        run_thread = threading.Thread(target=_run_target, daemon=True)
        run_thread.start()

        grace_passes_remaining = 2  # extra syncs after the run finishes, to catch trailing sub-agent output
        try:
            while True:
                waker.wait(timeout=POLL_FALLBACK_INTERVAL)
                self._sync_all()
                if run_done.is_set():
                    if grace_passes_remaining <= 0:
                        break
                    grace_passes_remaining -= 1
        finally:
            waker.stop()

        if run_error:
            raise run_error[0]

        root = self.nodes[root_session_id]
        # Prefer generate()'s own return value (authoritative); fall back to
        # scanning message history only if it came back empty for some reason.
        reply = run_result[0] if run_result and run_result[0] else self._final_text(root_session_id)
        self._emit(
            root, key=(root_session_id, "final"), kind="final", data={"reply": reply}
        )
        return reply

    # -- emitting -----------------------------------------------------------

    def _emit(
        self,
        node: SessionNode,
        key: EventKey,
        kind: str,
        name: Optional[str] = None,
        status: Optional[str] = None,
        data: Optional[dict] = None,
        parent_key: Optional[EventKey] = None,
    ) -> None:
        self.on_event(Event(
            ts=time.time(),
            session_id=node.session_id,
            depth=node.depth,
            key=key,
            parent_key=parent_key if parent_key is not None else node.spawn_key,
            kind=kind,
            name=name,
            status=status,
            data=data or {},
        ))

    # -- syncing --------------------------------------------------------------

    def _sync_all(self) -> None:
        # iterate over a snapshot since _sync_node may add new nodes (children)
        for node in list(self.nodes.values()):
            self._sync_node(node)

    def _sync_node(self, node: SessionNode) -> None:
        try:
            info = self.client.get_session(node.session_id)
        except requests.exceptions.RequestException as e:
            self._note_poll_failure(node, e)
            return
        try:
            messages = self.client.get_messages(node.session_id, order="asc")
        except requests.exceptions.RequestException as e:
            self._note_poll_failure(node, e)
            return

        # Both calls succeeded — clear any prior failure streak.
        node.consecutive_poll_failures = 0
        node.poll_failure_reported = False

        node.model_ref = info.get("model")
        self._maybe_emit_status(node, info)
        self._maybe_emit_session_error(node, info)

        for message in messages:
            self._handle_message(node, message)

    def _note_poll_failure(self, node: SessionNode, exc: Exception) -> None:
        """Polling GET /session or /message failed. A single blip isn't
        worth interrupting the log for (transient network hiccups happen),
        but if this keeps failing, silently doing nothing would be
        indistinguishable from 'the agent genuinely isn't doing anything' —
        which is exactly the ambiguity that makes a hung run hard to debug.
        So: report once after a few consecutive failures, so it's clear the
        problem is 'we can't observe the session' rather than 'nothing is
        happening in it'."""
        node.consecutive_poll_failures += 1
        threshold = 3  # ~3 poll cycles of sustained failure before flagging
        if node.consecutive_poll_failures >= threshold and not node.poll_failure_reported:
            node.poll_failure_reported = True
            self._emit(
                node, key=(node.session_id, "poll-failure"), kind="error",
                data={
                    "message": (
                        f"lost the ability to poll this session {node.consecutive_poll_failures} times in a row "
                        f"(most recent error: {exc}). The agent may still be running server-side — /wait is a "
                        f"separate request — but this client can no longer observe its progress. If this "
                        f"persists, the log going quiet does NOT mean the agent has stopped."
                    )
                },
            )

    def _maybe_emit_session_error(self, node: SessionNode, info: dict) -> None:
        err = info.get("error")
        if not err:
            return
        key = (node.session_id, "session-error")
        if node.part_state.get(key, {}).get("reported"):
            return
        node.part_state[key] = {"reported": True}
        self._emit(
            node, key=key, kind="error",
            data={"error": err, "message": f"session error: {_short_repr(err, 500)}"},
        )

    def _maybe_emit_status(self, node: SessionNode, info: dict) -> None:
        tokens = info.get("tokens") or {}
        cost = info.get("cost")
        ctx_limit = self.catalog.context_limit(node.model_ref)
        ctx_used = tokens.get("input", 0) + (tokens.get("cache", {}) or {}).get("read", 0)
        pct = f"{(ctx_used / ctx_limit * 100):.1f}%" if ctx_limit else None
        line = f"{node.label}|{fmt_tokens(tokens)}|{ctx_used}|{ctx_limit}|{cost}"
        if line == node.last_status_line:
            return
        node.last_status_line = line
        self._emit(
            node,
            key=(node.session_id, "status"),
            kind="status",
            data={
                "label": node.label,
                "tokens": tokens,
                "tokens_str": fmt_tokens(tokens),
                "cost": cost,
                "context_used": ctx_used,
                "context_limit": ctx_limit,
                "context_pct": pct,
            },
        )

    def _handle_message(self, node: SessionNode, message: dict) -> None:
        msg_id = message.get("id")
        msg_type = message.get("type")

        if msg_type == "assistant":
            self._handle_assistant_content(node, message)
            return  # assistant messages update incrementally; no header event needed

        if msg_id in node.known_message_ids:
            return
        node.known_message_ids.add(msg_id)
        key = (node.session_id, msg_id)

        if msg_type == "skill":
            name = message.get("name", message.get("skill"))
            self._emit(node, key=key, kind="skill", name=name)
        elif msg_type == "agent-switched":
            self._emit(node, key=key, kind="agent-switched", name=message.get("agent"))
        elif msg_type == "model-switched":
            m = message.get("model", {})
            self._emit(node, key=key, kind="model-switched", data=m)
        elif msg_type == "user":
            text = (message.get("text") or "").strip()
            if text:
                preview = text if len(text) <= 300 else text[:300] + "…"
                self._emit(node, key=key, kind="user", data={"preview": preview, "text": text})
        elif msg_type == "compaction":
            self._emit(
                node, key=key, kind="compaction",
                status=message.get("status"), data={"reason": message.get("reason")},
            )
        elif msg_type in ("synthetic", "system"):
            pass  # intentionally low-signal, not emitted
        else:
            # Anything not explicitly handled above (including message types
            # this script doesn't yet know about) is still surfaced, rather
            # than silently dropped, so failures aren't invisible.
            self._emit(
                node, key=key, kind="unknown", name=msg_type,
                data={"message": f"unrecognized message type '{msg_type}': {_short_repr(message, 500)}"},
            )

    def _handle_assistant_content(self, node: SessionNode, message: dict) -> None:
        msg_id = message.get("id")
        node.known_message_ids.add(msg_id)

        err = message.get("error")
        if err:
            key = (node.session_id, msg_id, "error")
            if not node.part_state.get(key, {}).get("reported"):
                node.part_state[key] = {"reported": True}
                self._emit(
                    node, key=key, kind="error",
                    data={"error": err, "message": f"assistant message error: {_short_repr(err, 500)}"},
                )

        content = message.get("content") or []

        for idx, part in enumerate(content):
            key = (node.session_id, msg_id, idx)
            ptype = part.get("type")

            if ptype == "text":
                self._emit_growing_text(node, key, part.get("text", ""), kind="text")
            elif ptype == "reasoning":
                self._emit_growing_text(node, key, part.get("text", ""), kind="reasoning")
            elif ptype == "tool":
                self._handle_tool_part(node, key, part)

    def _emit_growing_text(self, node: SessionNode, key: EventKey, text: str, kind: str) -> None:
        prev = node.part_state.get(key, {})
        prev_len = prev.get("len", 0)
        if len(text) <= prev_len:
            return
        delta = text[prev_len:][:TEXT_PREVIEW_CHARS]
        node.part_state[key] = {"len": len(text)}
        self._emit(
            node, key=key, kind=kind, status="delta",
            data={"delta": delta, "full_len": len(text)},
        )

    def _handle_tool_part(self, node: SessionNode, key: EventKey, part: dict) -> None:
        name = part.get("name", "?")
        state = part.get("state") or {}
        status = state.get("status")
        prev = node.part_state.get(key, {})

        if prev.get("status") == status:
            return  # no change to report
        node.part_state[key] = {**prev, "status": status}

        if status in ("streaming", "running"):
            self._emit(
                node, key=key, kind="tool", name=name, status=status,
                data={"input": state.get("input"), "input_preview": _short_repr(state.get("input"))},
            )
        elif status == "completed":
            output_text = _tool_content_text(state.get("content"))
            self._emit(
                node, key=key, kind="tool", name=name, status=status,
                data={"output": output_text, "output_preview": _short_repr(output_text)},
            )
        elif status == "error":
            err = (state.get("error") or {}).get("message", "unknown error")
            self._emit(node, key=key, kind="tool", name=name, status=status, data={"error": err})

        if name == "task" and status in ("running", "completed") and key not in node.spawned_children:
            self._discover_child_session(node, key)

    def _discover_child_session(self, node: SessionNode, tool_key: EventKey) -> None:
        node.spawned_children.add(tool_key)
        try:
            all_sessions = self.client.list_sessions()
        except requests.exceptions.RequestException:
            return
        candidates = [
            s for s in all_sessions
            if s.get("parentID") == node.session_id
            and s.get("id") not in self.nodes
            and s.get("id") not in node.claimed_child_ids
        ]
        if not candidates:
            return
        candidates.sort(key=lambda s: (s.get("time") or {}).get("created", 0))
        child = candidates[0]
        child_id = child["id"]
        node.claimed_child_ids.add(child_id)
        label = f"subagent:{child.get('agent', '?')}"

        child_node = SessionNode(
            session_id=child_id, parent_id=node.session_id, depth=node.depth + 1,
            label=label, spawn_key=tool_key,
        )
        self.nodes[child_id] = child_node

        self._emit(
            node, key=(node.session_id, child_id), parent_key=tool_key,
            kind="subagent-spawned", name=label, data={"child_session_id": child_id},
        )

    def _final_text(self, session_id: str) -> str:
        try:
            messages = self.client.get_messages(session_id, order="desc", limit=20)
        except requests.exceptions.RequestException:
            return ""
        for message in messages:
            if message.get("type") == "assistant":
                parts = [
                    p.get("text", "") for p in (message.get("content") or []) if p.get("type") == "text"
                ]
                if parts:
                    return "\n".join(parts)
        return ""


def _short_repr(value: Any, limit: int = 200) -> str:
    text = value if isinstance(value, str) else str(value)
    text = text.replace("\n", " ")
    return text if len(text) <= limit else text[:limit] + "…"


def _tool_content_text(content: Any) -> str:
    if not isinstance(content, list):
        return ""
    parts = [c.get("text", "") for c in content if isinstance(c, dict) and c.get("type") == "text"]
    return " ".join(parts)


# --------------------------------------------------------------------------
# chat(): the importable entry point (used directly by CLI's main(), and by
# library callers such as LangGraph nodes)
# --------------------------------------------------------------------------

def chat(args: argparse.Namespace, on_event: Optional[Listener] = None) -> str:
    """Runs one prompt to completion against an OpenCode 2 server and returns
    the final assistant reply as a string.

    `args` is any object with the attributes defined by the CLI parser below
    (base_url, username, password, directory, agent, skill, provider, model,
    variant, prompt, title, timeout, quiet, log_file) — an argparse.Namespace
    built by main(), or one you construct yourself when calling chat() as a
    library function.

    `on_event`, if given, receives every `Event` produced during the run —
    thinking deltas, tool-call transitions, skill activation, sub-agent
    discovery, token/context/cost updates, and a final "final" event with
    the completed reply. This is the integration point for LangSmith,
    structured logging, or any other observability tool; see the module
    docstring. If omitted, a default listener is chosen based on `args`:
    stdout (unless --quiet), or a file if --log-file was given.
    """
    close_ctx = None
    if on_event is None:
        if getattr(args, "quiet", False):
            on_event = null_listener
        elif getattr(args, "log_file", None):
            close_ctx = file_listener(args.log_file)
            on_event = close_ctx.__enter__()
        else:
            on_event = make_stream_listener()

    try:
        if bool(args.provider) != bool(args.model):
            raise ValueError("--provider and --model must be given together")

        client = OpenCodeClient(args.base_url, username=args.username, password=args.password)
        client.health()

        resolved_agent = client.resolve_agent(args.directory, args.agent)
        session_id = client.create_session(
            directory=args.directory,
            agent=resolved_agent,
            title=args.title,
            provider_id=args.provider,
            model_id=args.model,
            variant=args.variant,
        )
        model_note = f", model={args.provider}/{args.model}" if args.provider else ""
        agent_note = f" (resolved from {args.agent!r})" if resolved_agent != args.agent else ""
        _root = SessionNode(session_id=session_id, parent_id=None, depth=0, label=f"root:{resolved_agent}")
        on_event(Event(
            ts=time.time(), session_id=session_id, depth=0,
            key=(session_id, "lifecycle:created"), parent_key=None, kind="lifecycle",
            name="session-created",
            data={"message": f"session created ({session_id}) agent={resolved_agent}{agent_note}, directory={args.directory}{model_note}"},
        ))

        if args.skill:
            resolved_skill = client.resolve_skill(args.directory, args.skill)
            client.activate_skill(session_id, resolved_skill, resume=False)
            resolved_note = f" (resolved to id={resolved_skill!r})" if resolved_skill != args.skill else ""
            on_event(Event(
                ts=time.time(), session_id=session_id, depth=0,
                key=(session_id, "lifecycle:skill"), parent_key=None, kind="lifecycle",
                name="skill-requested", data={"message": f"skill requested: {args.skill}{resolved_note}"},
            ))

        on_event(Event(
            ts=time.time(), session_id=session_id, depth=0,
            key=(session_id, "lifecycle:prompt"), parent_key=None, kind="lifecycle",
            name="prompt-started", data={"message": "prompt sent (resume=True), running agent loop..."},
        ))

        def _run_full_agent_loop() -> str:
            client.send_prompt(session_id, args.prompt, resume=True)
            client.wait(session_id, timeout=args.timeout)
            return ""  # Monitor.run() falls back to scanning message history for the real reply

        catalog = ModelCatalog(client)
        monitor = Monitor(client, catalog, on_event=on_event)
        return monitor.run(
            session_id,
            root_agent_label=f"root:{resolved_agent}",
            run_fn=_run_full_agent_loop,
        )
    finally:
        if close_ctx is not None:
            close_ctx.__exit__(None, None, None)


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run a prompt on a local OpenCode server with live visibility")
    parser.add_argument("--base-url", default=os.environ.get("OPENCODE_URL", DEFAULT_BASE_URL),
                         help="Base URL of the running opencode server (default: http://localhost:4096)")
    parser.add_argument("--username", default=None,
                         help="Basic auth username (default: 'opencode', or $OPENCODE_SERVER_USERNAME)")
    parser.add_argument("--password", default=None,
                         help="Basic auth password (default: $OPENCODE_PASSWORD / $OPENCODE_SERVER_PASSWORD). "
                              "Required if the server was started without an explicit password, since opencode2 "
                              "then generates a random one and prints it to its own console at startup.")
    parser.add_argument("--directory", default=os.getcwd(),
                         help="Project directory the session should be scoped to (default: cwd)")
    parser.add_argument("--agent", required=True, help="Agent name to use for the session, e.g. 'build' or 'plan'")
    parser.add_argument("--skill", default=None, help="Skill name to activate before prompting (optional)")
    parser.add_argument("--provider", default=None, help="Provider ID to use, e.g. 'anthropic' (requires --model)")
    parser.add_argument("--model", default=None, help="Model ID to use, e.g. 'claude-sonnet-5' (requires --provider)")
    parser.add_argument("--variant", default=None, help="Optional model variant")
    parser.add_argument("--prompt", required=True, help="The prompt text to send")
    parser.add_argument("--title", default=None, help="Optional session title")
    parser.add_argument("--timeout", type=float, default=600.0, help="Max seconds to wait for a reply")
    parser.add_argument("--quiet", action="store_true", help="Suppress live output; print only the final answer")
    parser.add_argument("--log-file", default=None,
                         help="Write live output here instead of stdout (ignored if --quiet)")
    return parser


def main():
    parser = build_arg_parser()
    args = parser.parse_args()

    try:
        reply = chat(args)
    except ValueError as e:
        parser.error(str(e))
        return
    except RuntimeError as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)
    except requests.exceptions.RequestException as e:
        print(f"Could not reach OpenCode server at {args.base_url}: {e}", file=sys.stderr)
        sys.exit(1)

    # This is the program's actual result, not a log line, so it's printed
    # directly regardless of --quiet/--log-file (which only affect the live
    # Event stream produced while the run is in progress).
    print(reply if reply else "(no text content returned)")


if __name__ == "__main__":
    main()