from __future__ import annotations

"""
Generated by GPT-5.5 via UW Purple
- Originally 3 files, now merged into one script

Convert scientific PDFs to RAG-ready JSONL chunks.

This script wraps Docling conversion with conservative cleanup, quality scoring,
neighbor-aware repair, downstream strategy tagging, quarantine output, and QA reporting. It is designed for
biomedical, toxicology, environmental chemistry, and related scientific PDFs.

Example:
    python ingest.py --pdf-folder ./pdfs --output-jsonl ./artifacts/raw/ingestion_stream.jsonl
"""

import argparse
import json
import re
import statistics
import time
import urllib.parse
import urllib.request
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Mapping, Optional

import difflib
import html
import unicodedata
import warnings

from docling.chunking import HybridChunker
from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions
from docling.document_converter import DocumentConverter, PdfFormatOption

from util import utc_now

TOKEN_RE = re.compile(r"\b\w+[\w.-]*\b")
SENTENCE_RE = re.compile(r"[^.!?]+[.!?]")
LOWERCASE_START_RE = re.compile(r"^[a-zα-ωμ]")
CAPTION_RE = re.compile(r"^\s*(?:fig(?:ure)?\.?|table|scheme)\s*\d*[A-Za-z]?", re.I)
TABLE_HINT_RE = re.compile(r"\b(?:table|auc|accuracy|sensitivity|specificity|ppv|npv|tp|fp|tn|fn|rmse|mae|q2|r2|p\s*[<=>])\b", re.I)
EQUATION_HINT_RE = re.compile(r"(^|\s)(?:=|≤|≥|±|∑|√|Δ|μ|σ|α|β|γ|λ|mol|mg/kg|µg/L|ng/L)(\s|$)")
REFERENCE_HEADING_RE = re.compile(r"^(?:\d+\.?\s*)?(references?|bibliography)$", re.I)
TERMINAL_RE = re.compile(r"[.!?。！？)\]}\"]\s*$")
LONG_TOKEN_RE = re.compile(r"\b[^\s]{90,}\b")
SCIENCE_SIGNAL_RE = re.compile(
    r"\b(?:toxicity|exposure|dose|response|endpoint|assay|compound|chemical|model|"
    r"cell|gene|protein|receptor|environmental|biomarker|metabol|ecotoxic|concentration|"
    r"activity|inhibition|validation|dataset|species|pollutant|contaminant)\b",
    re.I,
)

PIPELINE_ID = "docling_hybrid_chunker_python_cleanup_v5_strategy_tagged"

DOWNSTREAM_INGESTION_STRATEGIES = {
    "A": "structural_decomposition",
    "B": "argument_centric_extraction",
    "C": "mechanism_or_case_extraction",
    "D": "definitional_procedural_extraction",
}


def token_count(text: str) -> int:
    return len(TOKEN_RE.findall(text or ""))


def sentence_count(text: str) -> int:
    return len(SENTENCE_RE.findall(text or ""))


def is_incomplete_end(text: str) -> bool:
    text = (text or "").strip()
    if not text:
        return True
    if TERMINAL_RE.search(text):
        return False
    if CAPTION_RE.search(text) and token_count(text) >= 50:
        return False
    if EQUATION_HINT_RE.search(text) and token_count(text) < 80:
        return False
    return True


def starts_lowercase(text: str) -> bool:
    return bool(LOWERCASE_START_RE.match((text or "").strip()))


def get_quality_flags(text: str, content_type: str, headings: list[str]) -> list[str]:
    flags: list[str] = []
    n_tokens = token_count(text)
    n_sentences = sentence_count(text)
    if n_tokens < 45:
        flags.append("short_chunk")
    if n_tokens > 450:
        flags.append("long_chunk")
    if starts_lowercase(text):
        flags.append("starts_lowercase")
    if is_incomplete_end(text):
        flags.append("ends_incomplete")
    if n_sentences == 0 and content_type not in {"equation", "table"}:
        flags.append("no_complete_sentence")
    if LONG_TOKEN_RE.search(text):
        flags.append("long_token")
    if content_type == "table" and "|" not in text and n_sentences < 2:
        flags.append("flattened_table_fragment")
    if any(REFERENCE_HEADING_RE.fullmatch(h.strip()) for h in headings):
        flags.append("reference_section")
    if text.count("\n") > 10 and n_tokens < 120:
        flags.append("layout_fragment")
    return flags


def score_rag_fitness(text: str, content_type: str, flags: list[str]) -> float:
    n_tokens = token_count(text)
    score = 1.0
    if n_tokens < 35:
        score -= 0.25
    elif n_tokens < 60:
        score -= 0.10
    if n_tokens > 420:
        score -= 0.20
    elif n_tokens > 360:
        score -= 0.10

    penalties = {
        "starts_lowercase": 0.10,
        "ends_incomplete": 0.15,
        "no_complete_sentence": 0.16,
        "long_token": 0.12,
        "flattened_table_fragment": 0.12,
        "reference_section": 0.35,
        "layout_fragment": 0.10,
    }
    for flag in flags:
        score -= penalties.get(flag, 0.05)

    if content_type in {"caption", "equation", "table"} and n_tokens >= 40:
        score += 0.05
    if SCIENCE_SIGNAL_RE.search(text or "") and n_tokens >= 45:
        score += 0.05
    return round(max(0.0, min(1.0, score)), 3)


def classify_content_type(text: str, headings: list[str]) -> str:
    stripped = (text or "").strip()
    lower_headings = " ".join(headings).lower()
    if CAPTION_RE.search(stripped):
        return "caption"
    if "abstract" in lower_headings:
        return "abstract"
    if any(REFERENCE_HEADING_RE.fullmatch(h.strip()) for h in headings):
        return "reference"
    if "|" in stripped or (TABLE_HINT_RE.search(stripped) and stripped.count("\n") >= 3):
        return "table"
    if EQUATION_HINT_RE.search(stripped) and sentence_count(stripped) <= 1:
        return "equation"
    return "main_text"


def _dedupe_sorted(values: Iterable[Any]) -> list[Any]:
    seen = set()
    out = []
    for value in values:
        if value in (None, ""):
            continue
        key = str(value)
        if key not in seen:
            out.append(value)
            seen.add(key)
    try:
        return sorted(out)
    except TypeError:
        return out


def _get_headings(chunk: Any) -> list[str]:
    candidates = [
        getattr(chunk, "headings", None),
        getattr(getattr(chunk, "meta", None), "headings", None),
        getattr(getattr(chunk, "meta", None), "headings_chain", None),
    ]
    for value in candidates:
        if value:
            if isinstance(value, str):
                return [value]
            return [str(x) for x in value if str(x).strip()]
    return []


def _get_page_numbers(chunk: Any) -> list[int]:
    pages: list[int] = []
    meta = getattr(chunk, "meta", None)
    candidates = [
        getattr(chunk, "page_numbers", None),
        getattr(meta, "page_numbers", None),
        getattr(meta, "pages", None),
        getattr(meta, "doc_items", None),
    ]
    for value in candidates:
        if not value:
            continue
        items = value if isinstance(value, (list, tuple, set)) else [value]
        for item in items:
            if isinstance(item, int):
                pages.append(item)
                continue
            page_no = getattr(item, "page_no", None) or getattr(item, "page_number", None)
            if page_no is not None:
                try:
                    pages.append(int(page_no))
                except Exception:
                    pass
            prov = getattr(item, "prov", None)
            if prov:
                for p in prov if isinstance(prov, (list, tuple)) else [prov]:
                    page_no = getattr(p, "page_no", None) or getattr(p, "page_number", None)
                    if page_no is not None:
                        try:
                            pages.append(int(page_no))
                        except Exception:
                            pass
    return _dedupe_sorted(pages)


def _safe_doc_export_text(result: Any) -> str:
    doc = getattr(result, "document", result)
    for name in ("export_to_markdown", "export_to_text"):
        fn = getattr(doc, name, None)
        if callable(fn):
            try:
                return str(fn())
            except Exception:
                continue
    return str(doc)


def _chunk_text(chunk: Any) -> str:
    return str(getattr(chunk, "text", "") or getattr(chunk, "content", "") or chunk)


def source_strategy_for(pdf_folder: Path, pdf_path: Path) -> dict[str, Any]:
    try:
        rel = pdf_path.relative_to(pdf_folder)
        first = rel.parts[0] if rel.parts else ""
    except ValueError:
        rel = pdf_path.name
        first = ""
    if first in DOWNSTREAM_INGESTION_STRATEGIES:
        return {
            "ingestion_strategy": first,
            "ingestion_strategy_name": DOWNSTREAM_INGESTION_STRATEGIES[first],
            "source_relative_path": str(rel),
            "source_strategy_folder": first,
            "strategy_is_assigned": True,
        }
    return {
        "ingestion_strategy": None,
        "ingestion_strategy_name": None,
        "source_relative_path": str(rel),
        "source_strategy_folder": None,
        "strategy_is_assigned": False,
    }


def build_converter() -> DocumentConverter:
    pdf_options = PdfPipelineOptions()
    pdf_options.do_ocr = False
    pdf_options.do_table_structure = True
    try:
        pdf_options.table_structure_options.do_cell_matching = True
    except Exception:
        pass
    return DocumentConverter(format_options={InputFormat.PDF: PdfFormatOption(pipeline_options=pdf_options)})


def iter_pdf_paths(pdf_folder: Path, pdf_glob: str) -> list[Path]:
    return sorted(pdf_folder.glob(pdf_glob))


def lookup_crossref_metadata(doi: str | None, mailto: str | None = None, timeout: int = 8) -> dict[str, Any]:
    doi = normalize_doi_candidate(doi)
    if not doi:
        return {}
    encoded = urllib.parse.quote(doi)
    url = f"https://api.crossref.org/works/{encoded}"
    if mailto:
        url += "?mailto=" + urllib.parse.quote(mailto)
    try:
        with urllib.request.urlopen(url, timeout=timeout) as response:
            payload = json.loads(response.read().decode("utf-8"))
        msg = payload.get("message", {})
        return {
            "title": (msg.get("title") or [None])[0],
            "container_title": (msg.get("container-title") or [None])[0],
            "published_print": msg.get("published-print"),
            "published_online": msg.get("published-online"),
            "publisher": msg.get("publisher"),
            "type": msg.get("type"),
            "doi": normalize_doi_candidate(msg.get("DOI")) or doi,
            "url": msg.get("URL"),
        }
    except Exception as exc:
        return {"doi_lookup_error": str(exc), "doi": doi}


def make_row(
    *,
    pdf_path: Path,
    chunk: Any,
    chunk_id: str,
    text: str,
    doi: str | None,
    document_metadata: dict[str, Any],
    source_info: dict[str, Any],
) -> dict[str, Any]:
    headings = _get_headings(chunk)
    pages = _get_page_numbers(chunk)
    content_type = classify_content_type(text, headings)
    flags = get_quality_flags(text, content_type, headings)
    rag_score = score_rag_fitness(text, content_type, flags)
    source_document_id = re.sub(r"[^a-zA-Z0-9_.-]+", "-", pdf_path.stem).strip("-").lower()
    extracted_dois = extract_dois(text)
    doi = normalize_doi_candidate(doi or (extracted_dois[0] if extracted_dois else None))
    record = {
        "chunk_id": chunk_id,
        "source_document_id": source_document_id,
        "source_document_name": pdf_path.name,
        "source_relative_path": source_info.get("source_relative_path", pdf_path.name),
        "page_numbers": pages,
        "headings": headings,
        "text": text,
        "content_type": content_type,
        "doi": doi,
        "extracted_dois": extracted_dois,
        "document_metadata": document_metadata,
        "quality_flags": flags,
        "rag_fitness_score": rag_score,
        "boundary_flags": {
            "starts_lowercase": starts_lowercase(text),
            "ends_incomplete": is_incomplete_end(text),
            "has_complete_sentence": sentence_count(text) > 0,
        },
        "token_count": token_count(text),
        "sentence_count": sentence_count(text),
        "ingestion_strategy": source_info.get("ingestion_strategy"),
        "ingestion_strategy_name": source_info.get("ingestion_strategy_name"),
        "strategy_is_assigned": source_info.get("strategy_is_assigned"),
        "source_strategy_folder": source_info.get("source_strategy_folder"),
        "pipeline_id": PIPELINE_ID,
        "created_at": utc_now(),
        "meta": {
            "source_document_id": source_document_id,
            "source_document_name": pdf_path.name,
            "source_relative_path": source_info.get("source_relative_path", pdf_path.name),
            "page_numbers": pages,
            "headings": headings,
            "content_type": content_type,
            "ingestion_strategy": source_info.get("ingestion_strategy"),
            "ingestion_strategy_name": source_info.get("ingestion_strategy_name"),
            "pipeline_id": PIPELINE_ID,
        },
    }
    return record


def merge_rows(a: dict[str, Any], b: dict[str, Any]) -> dict[str, Any]:
    merged = dict(a)
    merged["chunk_id"] = f"{a['chunk_id']}__merge__{b['chunk_id']}"
    merged["text"] = (a.get("text", "").rstrip() + "\n\n" + b.get("text", "").lstrip()).strip()
    merged["page_numbers"] = _dedupe_sorted(list(a.get("page_numbers", [])) + list(b.get("page_numbers", [])))
    merged["headings"] = _dedupe_sorted(list(a.get("headings", [])) + list(b.get("headings", [])))
    merged["content_type"] = classify_content_type(merged["text"], merged["headings"])
    merged["quality_flags"] = get_quality_flags(merged["text"], merged["content_type"], merged["headings"])
    merged["rag_fitness_score"] = score_rag_fitness(merged["text"], merged["content_type"], merged["quality_flags"])
    merged["boundary_flags"] = {
        "starts_lowercase": starts_lowercase(merged["text"]),
        "ends_incomplete": is_incomplete_end(merged["text"]),
        "has_complete_sentence": sentence_count(merged["text"]) > 0,
    }
    merged["token_count"] = token_count(merged["text"])
    merged["sentence_count"] = sentence_count(merged["text"])
    merged["source_chunk_ids"] = list(dict.fromkeys(a.get("source_chunk_ids", [a["chunk_id"]]) + b.get("source_chunk_ids", [b["chunk_id"]])))
    merged["merge_reason"] = "neighbor_boundary_repair"
    merged["meta"] = dict(merged.get("meta") or {})
    merged["meta"].update({
        "page_numbers": merged["page_numbers"],
        "headings": merged["headings"],
        "content_type": merged["content_type"],
        "source_chunk_ids": merged["source_chunk_ids"],
    })
    return merged


def postprocess_rows(rows: list[dict[str, Any]], min_merge_tokens: int, max_merge_tokens: int) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    merged: list[dict[str, Any]] = []
    i = 0
    while i < len(rows):
        row = rows[i]
        should_try_merge = (
            (row.get("token_count", 0) < min_merge_tokens or row.get("boundary_flags", {}).get("ends_incomplete"))
            and i + 1 < len(rows)
            and row.get("content_type") not in {"reference"}
        )
        if should_try_merge:
            candidate = merge_rows(row, rows[i + 1])
            if candidate.get("token_count", 0) <= max_merge_tokens and candidate.get("rag_fitness_score", 0) >= row.get("rag_fitness_score", 0):
                merged.append(candidate)
                i += 2
                continue
        merged.append(row)
        i += 1

    kept: list[dict[str, Any]] = []
    quarantined: list[dict[str, Any]] = []
    for row in merged:
        reason = drop_reason(row)
        if reason is None:
            kept.append(row)
        else:
            q = dict(row)
            q["quarantine_reason"] = reason
            q["quarantined_at"] = utc_now()
            quarantined.append(q)
    return kept, quarantined


def update_qa(
    qa: dict[str, Any],
    *,
    pdf_name: str,
    original: int,
    kept: list[dict[str, Any]],
    quarantine: list[dict[str, Any]],
    source_info: dict[str, Any],
    error: str | None = None,
) -> None:
    totals = qa["totals"]
    totals["documents_processed"] += 1
    if error:
        totals["documents_failed"] += 1
    totals["original_chunks"] += original
    totals["kept_chunks"] += len(kept)
    totals["quarantined_chunks"] += len(quarantine)
    totals["ingestion_strategies"].update([source_info.get("ingestion_strategy") or "unassigned"])
    for row in kept:
        totals["quality_flags"].update(row.get("quality_flags", []))
        totals["content_types"].update([row.get("content_type")])
        totals["rag_fitness_scores"].append(row.get("rag_fitness_score", 0))
    for row in quarantine:
        totals["quarantine_reasons"].update([row.get("quarantine_reason", "unknown")])

    qa["documents"][pdf_name] = {
        "error": error,
        "original_chunks": original,
        "kept_chunks": len(kept),
        "quarantined_chunks": len(quarantine),
        "source_relative_path": source_info.get("source_relative_path"),
        "ingestion_strategy": source_info.get("ingestion_strategy"),
        "ingestion_strategy_name": source_info.get("ingestion_strategy_name"),
        "strategy_is_assigned": source_info.get("strategy_is_assigned"),
        "kept_quality_flags": dict(Counter(flag for row in kept for flag in row.get("quality_flags", []))),
        "content_types": dict(Counter(row.get("content_type") for row in kept)),
        "quarantine_reasons": dict(Counter(row.get("quarantine_reason", "unknown") for row in quarantine)),
        "high_risk_chunks": sum(row.get("rag_fitness_score", 0) < 0.55 for row in kept),
        "incomplete_boundary_chunks": sum(row.get("boundary_flags", {}).get("ends_incomplete") for row in kept),
    }


def finalize_qa(qa: dict[str, Any], major_change_count: int) -> dict[str, Any]:
    totals = qa["totals"]
    scores = totals.pop("rag_fitness_scores", [])
    totals["quality_flags"] = dict(totals["quality_flags"])
    totals["content_types"] = dict(totals["content_types"])
    totals["quarantine_reasons"] = dict(totals["quarantine_reasons"])
    totals["ingestion_strategies"] = dict(totals["ingestion_strategies"])
    totals["major_change_records"] = major_change_count
    kept = max(totals.get("kept_chunks", 0), 1)
    totals["high_risk_chunk_ratio"] = round(
        sum(doc.get("high_risk_chunks", 0) for doc in qa["documents"].values()) / kept,
        6,
    )
    totals["incomplete_boundary_ratio"] = round(
        sum(doc.get("incomplete_boundary_chunks", 0) for doc in qa["documents"].values()) / kept,
        6,
    )
    totals["unassigned_strategy_documents"] = sum(
        1 for doc in qa["documents"].values() if not doc.get("strategy_is_assigned")
    )
    if scores:
        totals["rag_fitness"] = {
            "mean": round(statistics.mean(scores), 4),
            "median": round(statistics.median(scores), 4),
            "min": round(min(scores), 4),
            "max": round(max(scores), 4),
        }
    else:
        totals["rag_fitness"] = {"mean": None, "median": None, "min": None, "max": None}
    qa["finalized_at"] = utc_now()
    return qa


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert scientific PDFs to strategy-tagged, RAG-ready JSONL without applying downstream ingestion logic.")
    parser.add_argument("--pdf-folder", default="./pdfs", help="Folder containing PDFs.")
    parser.add_argument("--pdf-glob", default="**/*.pdf", help="Glob pattern relative to pdf-folder.")
    parser.add_argument("--md-folder", default="./mds", help="Folder for Docling Markdown exports.")
    parser.add_argument("--txt-folder", default="./txts", help="Folder for concatenated cleaned text exports.")
    parser.add_argument("--output-jsonl", default="./ingestion_stream.jsonl", help="Path for kept JSONL chunks.")
    parser.add_argument("--quarantine-jsonl", default="./quarantine_stream.jsonl", help="Path for quarantined JSONL chunks.")
    parser.add_argument("--qa-report", default="./ingestion_qa_report.json", help="Path for aggregate QA JSON report.")
    parser.add_argument("--major-change-report", default="./major_change_report.json", help="Path for cleaner diff report.")
    parser.add_argument("--log-folder", default=None, help="Optional folder for per-skill execution logs.")
    parser.add_argument("--no-crossref", action="store_true", help="Disable Crossref metadata lookup.")
    parser.add_argument("--crossref-mailto", default=None, help="Optional email for polite Crossref requests.")
    parser.add_argument("--min-merge-tokens", type=int, default=80, help="Chunks below this may merge with neighbors.")
    parser.add_argument("--max-merge-tokens", type=int, default=340, help="Maximum merged chunk token count.")
    parser.add_argument("--limit", type=int, default=None, help="Optional max PDFs to process.")
    return parser.parse_args()

def run_pipeline(args: argparse.Namespace):
    pdf_folder = Path(args.pdf_folder)
    md_folder = Path(args.md_folder)
    txt_folder = Path(args.txt_folder)
    log_folder = Path(args.log_folder) if args.log_folder else None
    for folder in (
        md_folder,
        txt_folder,
        Path(args.output_jsonl).parent,
        Path(args.quarantine_jsonl).parent,
        Path(args.qa_report).parent,
        Path(args.major_change_report).parent,
        *( [log_folder] if log_folder else [] ),
    ):
        folder.mkdir(parents=True, exist_ok=True)
    execution_log: list[dict[str, Any]] = []

    converter = build_converter()
    chunker = HybridChunker()
    major_change_report: dict[str, Any] = {}
    qa: dict[str, Any] = {
        "created_at": utc_now(),
        "pipeline_id": PIPELINE_ID,
        "downstream_ingestion_strategies": DOWNSTREAM_INGESTION_STRATEGIES,
        "parameters": vars(args),
        "documents": {},
        "totals": {
            "documents_processed": 0,
            "documents_failed": 0,
            "original_chunks": 0,
            "kept_chunks": 0,
            "quarantined_chunks": 0,
            "quality_flags": Counter(),
            "content_types": Counter(),
            "quarantine_reasons": Counter(),
            "ingestion_strategies": Counter(),
            "rag_fitness_scores": [],
        },
    }

    pdf_paths = iter_pdf_paths(pdf_folder, args.pdf_glob)
    if args.limit:
        pdf_paths = pdf_paths[: args.limit]

    with open(args.output_jsonl, "w", encoding="utf-8") as kept_out, open(args.quarantine_jsonl, "w", encoding="utf-8") as quarantine_out:
        for pdf_path in pdf_paths:
            original_n_chunks = 0
            kept_rows: list[dict[str, Any]] = []
            quarantine_rows: list[dict[str, Any]] = []
            source_info = source_strategy_for(pdf_folder, pdf_path)
            try:
                print(f"Processing {pdf_path}...")
                result = converter.convert(pdf_path)
                doc_text = _safe_doc_export_text(result)
                document = getattr(result, "document", result)
                chunks = list(chunker.chunk(dl_doc=document))
                original_n_chunks = len(chunks)

                front_matter = "\n".join(_chunk_text(chunk) for chunk in chunks[:10])
                dois = extract_dois(front_matter)
                doi = normalize_doi_candidate(dois[0]) if dois else None

                document_metadata = {} if args.no_crossref else lookup_crossref_metadata(doi, mailto=args.crossref_mailto)
                (md_folder / f"{pdf_path.stem}.md").write_text(doc_text, encoding="utf-8")

                candidate_rows = []
                for i, chunk in enumerate(chunks):
                    chunk_id = f"{pdf_path.stem}_chunk_{i}"
                    raw_text = str(getattr(chunk, "text", "") or "")
                    headings = _get_headings(chunk)
                    page_numbers = _get_page_numbers(chunk)
                    cleaned = clean_good_chunk(
                        raw_text,
                        chunk_id=chunk_id,
                        major_change_report=major_change_report,
                        report_context={"document_name": pdf_path.name, "page_numbers": page_numbers, "headings": headings, "pipeline_id": PIPELINE_ID, "ingestion_strategy": source_info.get("ingestion_strategy")},
                    )
                    row = make_row(pdf_path=pdf_path, chunk=chunk, chunk_id=chunk_id, text=cleaned, doi=doi, document_metadata=document_metadata, source_info=source_info)
                    candidate_rows.append(row)

                kept_rows, quarantine_rows = postprocess_rows(candidate_rows, min_merge_tokens=args.min_merge_tokens, max_merge_tokens=args.max_merge_tokens)

                for row in kept_rows:
                    kept_out.write(json.dumps(row, ensure_ascii=False) + "\n")
                for row in quarantine_rows:
                    quarantine_out.write(json.dumps(row, ensure_ascii=False) + "\n")

                (txt_folder / f"{pdf_path.stem}.txt").write_text("\n\n".join(row["text"] for row in kept_rows), encoding="utf-8")
                update_qa(qa, pdf_name=pdf_path.name, original=original_n_chunks, kept=kept_rows, quarantine=quarantine_rows, source_info=source_info)
                message = f"kept={len(kept_rows)} quarantined={len(quarantine_rows)} original={original_n_chunks}"
                print(f"  {message}")
                execution_log.append({
                    "timestamp": utc_now(),
                    "level": "info",
                    "document": pdf_path.name,
                    "message": message,
                    "ingestion_strategy": source_info.get("ingestion_strategy"),
                })
                time.sleep(0.05)

            except Exception as exc:
                error = str(exc)
                print(f"Error processing {pdf_path.name}: {error}")
                execution_log.append({
                    "timestamp": utc_now(),
                    "level": "error",
                    "document": pdf_path.name,
                    "message": error,
                    "ingestion_strategy": source_info.get("ingestion_strategy"),
                })
                update_qa(qa, pdf_name=pdf_path.name, original=original_n_chunks, kept=kept_rows, quarantine=quarantine_rows, source_info=source_info, error=error)

    major_count = write_major_change_report(major_change_report, args.major_change_report)
    qa = finalize_qa(qa, major_count)
    Path(args.qa_report).write_text(json.dumps(qa, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Extraction complete. Kept chunks: {args.output_jsonl}")
    print(f"Quarantine stream: {args.quarantine_jsonl}")
    print(f"QA report: {args.qa_report}")
    print(f"Major change report: {args.major_change_report} ({major_count} entries)")
    if log_folder:
        log_record = {
            "created_at": utc_now(),
            "pipeline_id": PIPELINE_ID,
            "parameters": vars(args),
            "summary": {
                "kept_jsonl": args.output_jsonl,
                "quarantine_jsonl": args.quarantine_jsonl,
                "qa_report": args.qa_report,
                "major_change_report": args.major_change_report,
                "major_change_entries": major_count,
            },
            "events": execution_log,
        }
        (log_folder / "pdf_to_jsonl_execution_log.json").write_text(
            json.dumps(log_record, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )

if __name__ == "__main__":
    args = parse_args()
    run(args)


######
### chunk_tosser
######

CAPTION_RE = re.compile(r"^\s*(figure|fig\.|table|scheme|supplementary)\s*\w*|\b(figure|fig\.|table|scheme|supplementary)\s*\d+", re.I)
YEAR_RE = re.compile(r"^(19|20)\d{2}$")
TOKEN_RE = re.compile(r"\b\w+[\w.-]*\b")
SENTENCE_RE = re.compile(r"[^.!?]+[.!?]")
URL_RE = re.compile(r"https?://|www\.|doi\.org|doi\s*:", re.I)
DOI_RE = re.compile(r"\b10\.\d{4,9}/[-._;()/:A-Z0-9]+\b", re.I)
EMAIL_RE = re.compile(r"\b[\w.+-]+@[\w.-]+\.\w+\b")
ORCID_RE = re.compile(r"\borcid\b|0000-\d{4}-\d{4}-\d{3}[\dX]\b", re.I)
KV_RE = re.compile(r"\b[A-Za-z][A-Za-z /()_-]{2,40}\s*[=:]")
TOC_DOTS_RE = re.compile(r"\.{6,}")
BIB_AUTHOR_RE = re.compile(r"\b[A-Z][A-Za-z'`-]+,\s*(?:[A-Z]\.?\s*){1,4}")
BIB_VOLUME_RE = re.compile(r"\b\d{1,4}\s*(?:\(\d+\))?\s*[:,]\s*\d{1,5}")
TABLE_METRIC_RE = re.compile(r"\b(?:auc|accuracy|sensitivity|specificity|ppv|npv|tp|fp|tn|fn|rmse|mae|r2|q2|ci|sd|sem|p\s*[<=>])\b", re.I)
SCIENCE_TERM_RE = re.compile(
    r"\b(?:toxicity|toxicology|chemical|compound|assay|exposure|dose|response|endpoint|"
    r"model|QSAR|AOP|adverse outcome|adverse outcome pathway|pathway|in vitro|in vivo|"
    r"IVIVE|read-across|read across|benchmark dose|BMD|point of departure|weight of evidence|"
    r"uncertainty|guidance|procedure|workflow|decision|regulatory|regulator|definition|defined as|"
    r"glossary|case study|mechanism|mode of action|molecular|receptor|gene|protein|cell|"
    r"environmental|biomarker|metabol|carcinogen|mutagen|ecotoxic|cytotoxicity|genotoxicity|"
    r"concentration|inhibition|activity|screening|dataset|validation|species|organism|water|"
    r"soil|sediment|pollutant|contaminant)\b",
    re.I,
)
FORMAL_DEFINITION_RE = re.compile(
    r"\b(?:is defined as|are defined as|means|refers to|is the process of|is a process by which|"
    r"should be|shall be|must be|recommended|guidance|procedure|workflow|step\s+\d+)\b",
    re.I,
)
DROP_SECTION_RE = re.compile(
    r"^(?:\d+\.?\s*)?(references?|bibliography|acknowledg(?:e)?ments?|funding|"
    r"author contributions?|credit authorship contribution statement|conflicts? of interest|"
    r"competing interests?|ethical approval|data availability|publisher'?s note|"
    r"correspondence|about the authors?)$",
    re.I,
)


def _extract_text(record: Any) -> str:
    if isinstance(record, str):
        return record
    if isinstance(record, Mapping):
        return str(record.get("text") or record.get("content") or "")
    return str(getattr(record, "text", "") or "")


def normalize_text(text: str) -> str:
    text = re.sub(r"/uniF[0-9A-Fa-f]{3,5}", " ", text or "")
    text = re.sub(r"[\u200b-\u200f\ufeff]", "", text)
    lines = []
    for raw in text.splitlines():
        line = re.sub(r"\s+", " ", raw).strip()
        if line and not re.fullmatch(r"\d{1,4}", line):
            lines.append(line)
    return "\n".join(lines).strip()


def _line_stats(text: str) -> dict[str, float]:
    lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
    if not lines:
        return {"line_count": 0, "short_line_ratio": 0.0, "one_token_line_ratio": 0.0, "year_line_ratio": 0.0}
    return {
        "line_count": len(lines),
        "short_line_ratio": sum(len(ln) < 35 for ln in lines) / len(lines),
        "one_token_line_ratio": sum(len(TOKEN_RE.findall(ln)) <= 1 for ln in lines) / len(lines),
        "year_line_ratio": sum(bool(YEAR_RE.fullmatch(ln)) for ln in lines) / len(lines),
    }


def chunk_features(text: str) -> dict[str, Any]:
    text = normalize_text(text)
    tokens = TOKEN_RE.findall(text)
    chars = max(len(text), 1)
    alpha = sum(ch.isalpha() for ch in text)
    numeric = sum(ch.isdigit() for ch in text)
    upper = sum(ch.isupper() for ch in text)
    lines = _line_stats(text)
    features = {
        "token_count": len(tokens),
        "sentence_count": len(SENTENCE_RE.findall(text)),
        "alpha_ratio": alpha / chars,
        "numeric_ratio": numeric / chars,
        "upper_ratio": upper / chars,
        "doi_count": len(DOI_RE.findall(text)),
        "email_count": len(EMAIL_RE.findall(text)),
        "orcid_count": len(ORCID_RE.findall(text)),
        "url_count": len(URL_RE.findall(text)),
        "kv_count": len(KV_RE.findall(text)),
        "pipe_count": text.count("|"),
        "toc_dot_count": len(TOC_DOTS_RE.findall(text)),
        "caption_like": bool(CAPTION_RE.search(text)),
        "table_metric_count": len(TABLE_METRIC_RE.findall(text)),
        "science_term_count": len(SCIENCE_TERM_RE.findall(text)),
        "formal_definition_count": len(FORMAL_DEFINITION_RE.findall(text)),
        "comma_count": text.count(","),
        "semicolon_count": text.count(";"),
        "long_token_count": sum(len(tok) > 80 for tok in tokens),
    }
    features.update(lines)
    return features


def _headings(record: Any) -> list[str]:
    if isinstance(record, Mapping):
        meta = record.get("meta") or {}
        value = meta.get("headings") or record.get("headings") or []
    else:
        value = getattr(record, "headings", []) or []
    if isinstance(value, str):
        return [value]
    return [str(x) for x in value if x]


def _in_drop_section(record: Any) -> bool:
    return any(DROP_SECTION_RE.fullmatch(h.strip()) for h in _headings(record))


def _compact_scientific(f: Mapping[str, Any]) -> bool:
    return (
        f["token_count"] >= 20
        and (f["science_term_count"] >= 2 or f.get("formal_definition_count", 0) >= 1)
        and f["alpha_ratio"] >= 0.58
        and f["email_count"] == 0
        and f["orcid_count"] == 0
    )


def _looks_bibliographic(text: str, f: Mapping[str, Any]) -> bool:
    hits = 0
    hits += 1 if BIB_AUTHOR_RE.search(text) else 0
    hits += 1 if BIB_VOLUME_RE.search(text) else 0
    hits += 1 if re.search(r"\b(et al\.|pp\.|vol\.|doi|pubmed|crossref|journal|elsevier|springer|wiley)\b", text, re.I) else 0
    hits += 1 if f["doi_count"] or f["url_count"] else 0
    return hits >= 3 and f["token_count"] < 190 and f["sentence_count"] <= 4


def _looks_supplement_notice(text: str, f: Mapping[str, Any]) -> bool:
    low = text.lower()
    if "supplementary" not in low and "supporting information" not in low:
        return False
    if f["token_count"] < 90:
        return True
    notice_terms = ("available online", "available at", "the following supporting information", "supplemental material")
    return any(term in low for term in notice_terms) and f["sentence_count"] <= 3


def _looks_boilerplate(text: str, f: Mapping[str, Any]) -> bool:
    low = text.lower()
    if (f["email_count"] or f["orcid_count"] > 1) and f["token_count"] < 150:
        return True
    if "corresponding author" in low and (EMAIL_RE.search(text) or "phone" in low):
        return True
    if "authors declare" in low and ("competing" in low or "conflict" in low):
        return f["token_count"] < 140
    if "all authors have given approval" in low:
        return True
    if all(word in low for word in ("received", "accepted", "published")):
        return f["token_count"] < 110
    if "creative commons" in low or "unless otherwise stated in a credit line" in low:
        return f["token_count"] < 140
    if "publisher's note" in low or "springer nature remains neutral" in low:
        return True
    return _looks_supplement_notice(text, f)


def _looks_table_debris(text: str, f: Mapping[str, Any]) -> bool:
    if f["sentence_count"] >= 3 and f["science_term_count"] >= 2:
        return False
    if f["pipe_count"] >= 2 and f["sentence_count"] < 3:
        return True
    if f["kv_count"] >= 4 and f["sentence_count"] < 3:
        return True
    if f["caption_like"] and f["short_line_ratio"] > 0.65 and (f["numeric_ratio"] > 0.10 or f["upper_ratio"] > 0.12):
        return True
    if f["table_metric_count"] >= 4 and f["numeric_ratio"] > 0.14 and f["sentence_count"] <= 2:
        return True
    if f["short_line_ratio"] > 0.45 and f["numeric_ratio"] > 0.18 and f["sentence_count"] < 2:
        return True
    return False


def drop_reason(record: Any) -> str | None:
    text = normalize_text(_extract_text(record))
    if not text:
        return "empty"
    if _in_drop_section(record):
        return "drop_section_heading"

    f = chunk_features(text)
    compact_scientific = _compact_scientific(f)
    definition_like = f.get("formal_definition_count", 0) >= 1 and f["token_count"] >= 15 and f["alpha_ratio"] >= 0.55

    if f["token_count"] < 12:
        return "too_short"
    if f["token_count"] < 20 and not compact_scientific and not definition_like:
        return "too_short"
    if f["sentence_count"] == 0 and f["token_count"] < 60:
        if (compact_scientific or definition_like) and not f["caption_like"] and f["numeric_ratio"] <= 0.22:
            return None
        if f["numeric_ratio"] > 0.12 or f["email_count"] or f["orcid_count"]:
            return "numeric_or_contact_fragment"
        if f["comma_count"] >= 4 or f["caption_like"] or f["pipe_count"]:
            return "fragment_without_sentence"
    if f["sentence_count"] <= 1 and f["token_count"] < 30 and not compact_scientific and not definition_like:
        return "short_single_sentence"
    if _looks_boilerplate(text, f):
        return "boilerplate_or_notice"
    if _looks_bibliographic(text, f):
        return "bibliographic_fragment"
    if f["toc_dot_count"] >= 2 or (f["toc_dot_count"] and f["numeric_ratio"] > 0.12):
        return "table_of_contents"
    if f["caption_like"] and (f["sentence_count"] <= 1 or f["token_count"] < 45) and not compact_scientific:
        return "orphan_caption"
    if _looks_table_debris(text, f):
        return "table_debris"
    if f["one_token_line_ratio"] > 0.30 and f["year_line_ratio"] > 0.10 and f["sentence_count"] < 2:
        return "reference_like_line_list"
    if f["alpha_ratio"] < 0.50 and f["numeric_ratio"] > 0.28 and f["sentence_count"] < 2:
        return "numeric_fragment"
    if f["long_token_count"] > 2 and f["token_count"] < 120:
        return "encoding_or_url_fragment"
    return None


def should_drop_text(text: str) -> bool:
    return drop_reason(text) is not None


def should_keep_chunk(record: Any) -> bool:
    return drop_reason(record) is None


######
### chunk_cleaner
######

"""Conservative PDF chunk cleanup helpers for scientific RAG ingestion.

The cleaner repairs common extraction artifacts while preserving evidence-bearing
scientific text. It also exposes DOI normalization and quality-warning helpers
used by ingest.py.
"""

CONTROL_RE = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")
ZERO_WIDTH_RE = re.compile(r"[\u200b-\u200f\u202a-\u202e\u2060\ufeff]")
PRIVATE_USE_RE = re.compile(r"/[Uu]ni[Ff][0-9A-Fa-f]{3,5}|[\ue000-\uf8ff]")
MULTISPACE_RE = re.compile(r"[ \t]{2,}")
MULTIBLANK_RE = re.compile(r"\n{3,}")
BROKEN_HYPHEN_RE = re.compile(r"(?<=[A-Za-z])[-\u2010-\u2015]\s*\n\s*(?=[a-z])")
SPACED_HYPHEN_RE = re.compile(r"(?<=[A-Za-z])\s+[-\u2010-\u2015]\s+(?=[A-Za-z])")
LINE_WRAP_RE = re.compile(r"(?<=[a-z,;:)])\n(?=[a-z(])")
SOFT_WRAP_RE = re.compile(r"(?<![.!?:;\n])\n(?!\s*[-*\u2022\d]+[.)]\s)(?=\S)")
DOI_SPACE_RE = re.compile(r"\b(10\.\d{4,9})\s*/\s*([^\s]+)", re.I)
DOI_LABEL_SPACE_RE = re.compile(r"\bdoi\s*[:：]\s*(10\.\d{4,9})\s*/\s*([^\s]+)", re.I)
URL_SPACE_RE = re.compile(r"\b(https?://|www\.)\s+", re.I)
URL_LINEBREAK_RE = re.compile(r"\b(https?://|www\.)\s*\n\s*", re.I)
DOI_URL_RE = re.compile(r"https?://(?:dx\.)?doi\.org/\s*", re.I)
FIGURE_SPACED_RE = re.compile(r"\b[fF]\s*[iI]\s*[gG]\s*[uU]\s*[rR]\s*[eE]\b")
TABLE_SPACED_RE = re.compile(r"\b[tT]\s*[aA]\s*[bB]\s*[lL]\s*[eE]\b")
REFERENCE_SPACED_RE = re.compile(r"\b[rR]\s*[eE]\s*[fF]\s*[eE]\s*[rR]\s*[eE]\s*[nN]\s*[cC]\s*[eE]\s*[sS]\b")
PIPE_EDGE_RE = re.compile(r"(?m)^\s*\|\s*|\s*\|\s*$")
DANGLING_PAGE_RE = re.compile(r"(?m)^\s*\d{1,4}\s*$")
REPEATED_PUNCT_RE = re.compile(r"([,.;:!?])\1{2,}")
LONG_TOKEN_RE = re.compile(r"\b[^\s]{90,}\b")

# DOI suffixes are intentionally bounded. 
# Broad DOI regexes often swallow article titles, licenses, or following prose after aggressive PDF line-joining.
DOI_CANDIDATE_RE = re.compile(
    r"(?:https?://(?:dx\.)?doi\.org/|doi\s*[:：]\s*)?"
    r"(10\.\d{4,9}\s*/\s*[-._;()/:A-Z0-9]+)",
    re.I,
)
DOI_STOPWORD_RE = re.compile(
    r"(?i)(?:abstract|introduction|keywords?|received|accepted|published|copyright|"
    r"creativecommons|license|thisarticle|availableonline|contentslists|journalhomepage)$"
)

UNICODE_REPLACEMENTS = {
    "\u00a0": " ", "\u1680": " ", "\u2000": " ", "\u2001": " ", "\u2002": " ",
    "\u2003": " ", "\u2004": " ", "\u2005": " ", "\u2006": " ", "\u2007": " ",
    "\u2008": " ", "\u2009": " ", "\u200a": " ", "\u202f": " ", "\u205f": " ",
    "\u3000": " ", "\u00ad": "", "\u2010": "-", "\u2011": "-", "\u2012": "-",
    "\u2013": "-", "\u2014": "-", "\u2015": "-", "\u2212": "-", "\u2018": "'",
    "\u2019": "'", "\u201a": "'", "\u201b": "'", "\u201c": '"', "\u201d": '"',
    "\u201e": '"', "\u201f": '"', "\u2026": "...", "\ufb00": "ff", "\ufb01": "fi",
    "\ufb02": "fl", "\ufb03": "ffi", "\ufb04": "ffl", "\ufb05": "st", "\ufb06": "st",
}

MOJIBAKE_REPLACEMENTS = {
    "â€™": "'", "â€˜": "'", "â€œ": '"', "â€": '"', "â€\u009d": '"',
    "â€“": "-", "â€”": "-", "â€¦": "...", "Â ": " ", "Â": "",
    "Ã—": "×", "Ã÷": "÷", "Î¼": "μ", "Î±": "α", "Î²": "β", "Î³": "γ",
    "Î´": "δ", "Îº": "κ", "Î»": "λ", "Ïƒ": "σ", "Ï„": "τ",
}


def _safe_len(text: str) -> int:
    return max(len(text), 1)


def _change_ratio(before: str, after: str) -> float:
    if not before:
        return 0.0 if not after else 1.0
    return abs(len(before) - len(after)) / float(_safe_len(before))


def _replace_many(text: str, replacements: dict[str, str]) -> str:
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


def _clean_lines(text: str) -> str:
    lines = []
    for line in text.splitlines():
        line = line.strip()
        line = MULTISPACE_RE.sub(" ", line)
        if line:
            lines.append(line)
    return "\n".join(lines)


def normalize_doi_candidate(text: Optional[str]) -> Optional[str]:
    """Return a valid DOI or None.

    This trims punctuation and common prose swallowed by PDF line joining. It is
    conservative: doubtful candidates are rejected instead of being sent to
    metadata services.
    """
    if not text:
        return None
    candidate = html.unescape(str(text)).strip()
    candidate = re.sub(r"^(?:https?://(?:dx\.)?doi\.org/|doi\s*[:：]\s*)", "", candidate, flags=re.I)
    candidate = re.sub(r"\s*/\s*", "/", candidate)
    candidate = re.sub(r"\s+", "", candidate)
    candidate = candidate.rstrip(".,;:)]}>}\"'")
    # DOI suffixes do not contain whitespace, but broad extraction may append words. 
    # Iteratively trim at low-confidence separators.
    for sep in ("|", "<", ">", "#"):
        candidate = candidate.split(sep, 1)[0]
    candidate = re.sub(r"(?i)(?:abstract|keywords?|introduction|received|accepted|published).*$", "", candidate)
    while DOI_STOPWORD_RE.search(candidate):
        candidate = re.sub(r"(?i)(abstract|keywords?|introduction|received|accepted|published|copyright|creativecommons|license|thisarticle|availableonline|contentslists|journalhomepage)$", "", candidate)
        candidate = candidate.rstrip(".,;:)]}>}\"'")
    if not re.fullmatch(r"10\.\d{4,9}/[-._;()/:A-Z0-9]+", candidate, flags=re.I):
        return None
    if len(candidate) > 160:  # almost always a swallowed-title artifact
        return None
    return candidate


def extract_dois(text: str, limit: int = 5) -> list[str]:
    """Extract normalized DOI candidates from text in first-seen order."""
    found = []
    for match in DOI_CANDIDATE_RE.finditer(text or ""):
        doi = normalize_doi_candidate(match.group(1))
        if doi and doi.lower() not in {x.lower() for x in found}:
            found.append(doi)
            if len(found) >= limit:
                break
    return found


def _normalize_broken_doi_and_url(text: str) -> str:
    text = DOI_LABEL_SPACE_RE.sub(r"doi:\1/\2", text)
    text = DOI_SPACE_RE.sub(r"\1/\2", text)
    text = DOI_URL_RE.sub("doi:", text)
    text = URL_LINEBREAK_RE.sub(r"\1", text)
    text = URL_SPACE_RE.sub(r"\1", text)
    # Only remove internal DOI spaces when the resulting candidate validates.
    def _repair(match: re.Match) -> str:
        joined = match.group(1) + match.group(2)
        return joined if normalize_doi_candidate(joined) else match.group(0)
    text = re.sub(r"\b(10\.\d{4,9}/[^\s,;]+)\s+([A-Za-z0-9._;()/:+-]+)", _repair, text)
    return text


def _unified_diff(before: str, after: str, chunk_id: Optional[str] = None, context_lines: int = 3) -> str:
    fromfile = f"{chunk_id}:original" if chunk_id else "original"
    tofile = f"{chunk_id}:cleaned" if chunk_id else "cleaned"
    return "".join(
        difflib.unified_diff(
            before.splitlines(keepends=True),
            after.splitlines(keepends=True),
            fromfile=fromfile,
            tofile=tofile,
            lineterm="",
            n=context_lines,
        )
    )


def _append_major_change(
    report,
    *,
    chunk_id,
    before,
    after,
    change_ratio,
    warn_threshold,
    context=None,
    diff_context_lines=3,
    max_text_chars=12000,
):
    if report is None:
        return
    normalized_chunk_id = chunk_id or "__unknown_chunk__"
    before_excerpt = before[:max_text_chars]
    after_excerpt = after[:max_text_chars]
    record = {
        "chunk_id": normalized_chunk_id,
        "change_ratio": round(change_ratio, 6),
        "warn_threshold": warn_threshold,
        "original_length": len(before),
        "cleaned_length": len(after),
        "length_delta": len(after) - len(before),
        "possible_over_pruning": len(after) < len(before) and change_ratio >= warn_threshold,
        "diff": _unified_diff(before_excerpt, after_excerpt, chunk_id=normalized_chunk_id, context_lines=diff_context_lines),
    }
    if context:
        record["context"] = context
    if len(before) > max_text_chars or len(after) > max_text_chars:
        record["diff_truncated"] = True
        record["max_text_chars"] = max_text_chars
    if isinstance(report, dict):
        report[normalized_chunk_id] = record
    elif hasattr(report, "append"):
        report.append(record)
    else:
        raise TypeError("major_change_report must be a dict, list, or list-like object with append().")


def write_major_change_report(report, path, *, as_json=True) -> int:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(report, dict):
        records_by_id = report
    else:
        records_by_id = {record.get("chunk_id", f"chunk_{i}"): record for i, record in enumerate(report or [])}
    if as_json:
        payload = {
            "created_at": datetime.now(timezone.utc).isoformat(),
            "entry_count": len(records_by_id),
            "chunks": records_by_id,
        }
        path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    else:
        with path.open("w", encoding="utf-8") as f:
            for record in records_by_id.values():
                f.write(json.dumps(record, ensure_ascii=False) + "\n")
    return len(records_by_id)


def clean_good_chunk(
    text,
    warn_threshold=0.35,
    *,
    chunk_id=None,
    major_change_report=None,
    report_context=None,
    diff_context_lines=3,
    max_report_text_chars=12000,
):
    """Normalize an already-plausible RAG chunk without semantic pruning.

    This function intentionally does not delete scientific content based on
    meaning. It fixes encoding, line wrap, DOI/URL, and punctuation artifacts and
    records major destructive changes for audit.
    """
    if text is None:
        text = ""
    if not isinstance(text, str):
        text = str(text)

    original = text
    cleaned = html.unescape(text)
    cleaned = unicodedata.normalize("NFKC", cleaned)
    cleaned = _replace_many(cleaned, UNICODE_REPLACEMENTS)
    cleaned = _replace_many(cleaned, MOJIBAKE_REPLACEMENTS)
    cleaned = CONTROL_RE.sub("", cleaned)
    cleaned = ZERO_WIDTH_RE.sub("", cleaned)
    cleaned = PRIVATE_USE_RE.sub(" ", cleaned)

    cleaned = cleaned.replace("\r\n", "\n").replace("\r", "\n")
    cleaned = BROKEN_HYPHEN_RE.sub("", cleaned)
    cleaned = SPACED_HYPHEN_RE.sub("-", cleaned)
    cleaned = LINE_WRAP_RE.sub(" ", cleaned)
    cleaned = SOFT_WRAP_RE.sub(" ", cleaned)

    cleaned = _normalize_broken_doi_and_url(cleaned)
    cleaned = FIGURE_SPACED_RE.sub("Figure", cleaned)
    cleaned = TABLE_SPACED_RE.sub("Table", cleaned)
    cleaned = REFERENCE_SPACED_RE.sub("References", cleaned)

    cleaned = PIPE_EDGE_RE.sub("", cleaned)
    cleaned = DANGLING_PAGE_RE.sub("", cleaned)
    cleaned = _clean_lines(cleaned)
    cleaned = re.sub(r"\s+([,.;:!?%)\]])", r"\1", cleaned)
    cleaned = re.sub(r"([(\[])\s+", r"\1", cleaned)
    cleaned = re.sub(r"\bdoi\s*:\s*", "doi:", cleaned, flags=re.I)
    cleaned = REPEATED_PUNCT_RE.sub(r"\1", cleaned)
    cleaned = MULTIBLANK_RE.sub("\n\n", cleaned).strip()

    ratio = _change_ratio(original, cleaned)
    if ratio >= warn_threshold:
        _append_major_change(
            major_change_report,
            chunk_id=chunk_id,
            before=original,
            after=cleaned,
            change_ratio=ratio,
            warn_threshold=warn_threshold,
            context=report_context,
            diff_context_lines=diff_context_lines,
            max_text_chars=max_report_text_chars,
        )
        id_msg = f" for chunk_id={chunk_id}" if chunk_id else " for unknown chunk_id"
        warnings.warn(
            "clean_good_chunk substantially altered text{} ({:.0%} length change); "
            "review major_change_report for possible over-pruning.".format(id_msg, ratio),
            RuntimeWarning,
            stacklevel=2,
        )
    return cleaned
