#!/usr/bin/env python3

"""
---
Generated by Claude.ai Sonnet 5 (Medium effort)
---

Run a prompt against a locally running OpenCode 2 server (HttpApi v2), with a
specific agent, skill, and provider/model — and stream live visibility into
what the agent is doing: thinking (reasoning), tool calls, skill use,
sub-agent invocations, and token / context-window usage, rendered as an
indented tree so sub-agent activity nests under the tool call that spawned it.

Requires OpenCode 2 running locally, e.g.:

    opencode2 serve --port 4096

Docs: https://opencode.ai/v2/docs/api

Usage:
    python opencode_run.py \
        --prompt "Refactor this function for clarity" \
        --agent build \
        --skill code-review \
        --provider anthropic \
        --model claude-sonnet-5 \
        --directory /path/to/your/project

Add --quiet to suppress the live tree and just print the final answer
(useful for scripting / piping).

--- Design notes / known assumptions ---

The v2 HttpApi is marked "experimental" and its SSE event payload shape
(GET /api/event) isn't documented beyond the outer envelope
{id, event, data}. Rather than depend on parsing that payload precisely,
this script uses the event stream only as a low-latency "something
changed, go re-sync" signal (falling back to polling on a fixed interval
regardless, so it degrades gracefully if SSE payload parsing ever fails
or the stream drops). The actual rendering is always driven by re-reading
GET /api/session/{id} and GET /api/session/{id}/message, so what you see
is always ground truth from the API, just possibly ~1 poll-interval late
if SSE didn't wake us early.

Sub-agent discovery: the model invokes sub-agents via a "task" tool.
There is no documented field linking a task-tool call directly to the
child session it spawns, so this script infers it heuristically: after a
"task" tool call appears, it lists all sessions and claims the newest
not-yet-claimed session whose parentID matches the current session. This
works well for the common case of sequential sub-agent calls; if an agent
fires many sub-agents in tight parallel, attribution to the *correct*
task call may be approximate (though every child session is still found
and rendered).
"""

import argparse
import os
import queue
import sys
import threading
import time
from dataclasses import dataclass, field
from typing import Any, Optional

import requests


DEFAULT_BASE_URL = "http://localhost:4096"
POLL_FALLBACK_INTERVAL = 1.5  # seconds; used when no SSE event wakes us up
TEXT_PREVIEW_CHARS = 4000     # cap how much of a single delta we print at once


# --------------------------------------------------------------------------
# HTTP client
# --------------------------------------------------------------------------

class OpenCodeClient:
    def __init__(
        self,
        base_url: str = DEFAULT_BASE_URL,
        username: str | None = None,
        password: str | None = None,
    ):
        self.base_url = base_url.rstrip("/")
        self.session = requests.Session()
        password = password or os.environ.get("OPENCODE_PASSWORD") or os.environ.get("OPENCODE_SERVER_PASSWORD")
        username = username or os.environ.get("OPENCODE_SERVER_USERNAME") or "opencode"
        if password:
            self.session.auth = requests.auth.HTTPBasicAuth(username, password)

    def _url(self, path: str) -> str:
        return f"{self.base_url}{path}"

    def _check_auth_error(self, resp: requests.Response) -> None:
        if resp.status_code == 401:
            raise RuntimeError(
                "OpenCode server rejected the request (401 Unauthorized). "
                "The server requires HTTP Basic Auth — pass --password (and --username "
                "if you changed it), or set OPENCODE_PASSWORD / OPENCODE_SERVER_PASSWORD. "
                "opencode2 prints the auto-generated password to its own stdout/log at "
                "startup if you didn't set one explicitly."
            )

    # -- health / misc -------------------------------------------------

    def health(self) -> dict:
        resp = self.session.get(self._url("/api/health"))
        self._check_auth_error(resp)
        resp.raise_for_status()
        return resp.json()

    # -- session lifecycle ----------------------------------------------

    def create_session(
        self,
        directory: str,
        agent: str | None = None,
        title: str | None = None,
        provider_id: str | None = None,
        model_id: str | None = None,
        variant: str | None = None,
    ) -> str:
        body: dict[str, Any] = {"location": {"directory": directory}}
        if agent:
            body["agent"] = agent
        if title:
            body["title"] = title
        if provider_id or model_id:
            if not (provider_id and model_id):
                raise ValueError("Both provider and model must be given together")
            model_ref = {"id": model_id, "providerID": provider_id}
            if variant:
                model_ref["variant"] = variant
            body["model"] = model_ref

        resp = self.session.post(self._url("/api/session"), json=body)
        self._check_auth_error(resp)
        resp.raise_for_status()
        return resp.json()["data"]["id"]

    def get_session(self, session_id: str) -> dict:
        resp = self.session.get(self._url(f"/api/session/{session_id}"))
        self._check_auth_error(resp)
        resp.raise_for_status()
        return resp.json()["data"]

    def list_sessions(self) -> list[dict]:
        resp = self.session.get(self._url("/api/session"))
        self._check_auth_error(resp)
        resp.raise_for_status()
        return resp.json()["data"]

    def switch_agent(self, session_id: str, agent: str) -> None:
        resp = self.session.post(
            self._url(f"/api/session/{session_id}/agent"), json={"agent": agent}
        )
        self._check_auth_error(resp)
        resp.raise_for_status()

    def switch_model(self, session_id: str, provider_id: str, model_id: str, variant: str | None = None) -> None:
        model_ref = {"id": model_id, "providerID": provider_id}
        if variant:
            model_ref["variant"] = variant
        resp = self.session.post(
            self._url(f"/api/session/{session_id}/model"), json={"model": model_ref}
        )
        self._check_auth_error(resp)
        resp.raise_for_status()

    def activate_skill(self, session_id: str, skill: str, resume: bool = False) -> None:
        resp = self.session.post(
            self._url(f"/api/session/{session_id}/skill"),
            json={"skill": skill, "resume": resume},
        )
        self._check_auth_error(resp)
        resp.raise_for_status()

    def send_prompt(self, session_id: str, text: str, resume: bool = True) -> dict:
        resp = self.session.post(
            self._url(f"/api/session/{session_id}/prompt"),
            json={"text": text, "resume": resume},
        )
        self._check_auth_error(resp)
        resp.raise_for_status()
        return resp.json()["data"]

    def wait(self, session_id: str, timeout: float = 600.0) -> None:
        """Blocks (server-side) until the session's agent loop goes idle."""
        resp = self.session.post(
            self._url(f"/api/session/{session_id}/wait"),
            timeout=timeout + 30,
        )
        if resp.status_code not in (200, 204):
            self._check_auth_error(resp)
            resp.raise_for_status()

    def get_messages(self, session_id: str, order: str = "asc", limit: int = 500) -> list[dict]:
        resp = self.session.get(
            self._url(f"/api/session/{session_id}/message"),
            params={"order": order, "limit": limit},
        )
        self._check_auth_error(resp)
        resp.raise_for_status()
        return resp.json()["data"]

    def list_models(self) -> list[dict]:
        resp = self.session.get(self._url("/api/model"))
        self._check_auth_error(resp)
        resp.raise_for_status()
        return resp.json()["data"]

    def event_stream(self):
        """Yields (event_name, raw_data_str) tuples from GET /api/event (SSE).
        Never raises out of the generator on transient errors — the caller
        (SSEWaker) treats any exception as "reconnect after a short pause".
        """
        with self.session.get(self._url("/api/event"), stream=True, timeout=None) as resp:
            self._check_auth_error(resp)
            resp.raise_for_status()
            event_name = None
            data_lines: list[str] = []
            for raw_line in resp.iter_lines(decode_unicode=True):
                if raw_line is None:
                    continue
                line = raw_line
                if line == "":
                    if data_lines:
                        yield (event_name, "\n".join(data_lines))
                    event_name, data_lines = None, []
                    continue
                if line.startswith("event:"):
                    event_name = line[len("event:"):].strip()
                elif line.startswith("data:"):
                    data_lines.append(line[len("data:"):].strip())
                # ignore "id:" and comment lines (":") — not needed here


# --------------------------------------------------------------------------
# Model catalog (for context-window sizing)
# --------------------------------------------------------------------------

class ModelCatalog:
    def __init__(self, client: OpenCodeClient):
        self.client = client
        self._by_provider_model: dict[tuple[str, str], int] = {}
        self._by_id: dict[str, int] = {}
        self._loaded = False

    def _load(self) -> None:
        try:
            for m in self.client.list_models():
                ctx = (m.get("limit") or {}).get("context")
                if not ctx:
                    continue
                self._by_provider_model[(m["providerID"], m["modelID"])] = ctx
                self._by_id[m["id"]] = ctx
        except requests.exceptions.RequestException:
            pass  # context-window display is best-effort
        self._loaded = True

    def context_limit(self, model_ref: dict | None) -> Optional[int]:
        if not model_ref:
            return None
        if not self._loaded:
            self._load()
        key = (model_ref.get("providerID"), model_ref.get("id"))
        if key in self._by_provider_model:
            return self._by_provider_model[key]
        return self._by_id.get(model_ref.get("id"))


# --------------------------------------------------------------------------
# Background "wake me on change" signal via SSE, with polling fallback
# --------------------------------------------------------------------------

class SSEWaker:
    def __init__(self, client: OpenCodeClient):
        self.client = client
        self._q: "queue.Queue[None]" = queue.Queue(maxsize=1)
        self._stop = threading.Event()
        self._thread = threading.Thread(target=self._run, daemon=True)

    def start(self) -> None:
        self._thread.start()

    def stop(self) -> None:
        self._stop.set()

    def _run(self) -> None:
        while not self._stop.is_set():
            try:
                for _event_name, _data in self.client.event_stream():
                    if self._stop.is_set():
                        return
                    self._nudge()
            except requests.exceptions.RequestException:
                pass
            if not self._stop.is_set():
                time.sleep(1.0)  # brief pause before reconnecting

    def _nudge(self) -> None:
        try:
            self._q.put_nowait(None)
        except queue.Full:
            pass

    def wait(self, timeout: float) -> bool:
        """Blocks until either an SSE event arrives or timeout elapses.
        Returns True if woken by an event, False on timeout (fallback poll)."""
        try:
            self._q.get(timeout=timeout)
            return True
        except queue.Empty:
            return False


# --------------------------------------------------------------------------
# Tree rendering
# --------------------------------------------------------------------------

def emit(depth: int, icon: str, text: str) -> None:
    prefix = "\u2502  " * depth  # "│  " per depth level
    for i, line in enumerate(text.splitlines() or [""]):
        marker = icon if i == 0 else "  "
        print(f"{prefix}{marker} {line}", flush=True)


def fmt_tokens(tokens: dict) -> str:
    cache = tokens.get("cache", {}) or {}
    return (
        f"in={tokens.get('input', 0)} out={tokens.get('output', 0)} "
        f"reasoning={tokens.get('reasoning', 0)} "
        f"cache(read={cache.get('read', 0)},write={cache.get('write', 0)})"
    )


@dataclass
class SessionNode:
    session_id: str
    parent_id: Optional[str]
    depth: int
    label: str
    known_message_ids: set = field(default_factory=set)
    part_state: dict = field(default_factory=dict)   # (message_id, idx) -> {"status": ..., "len": ...}
    spawned_children: set = field(default_factory=set)  # tool part ids already resolved to a child session
    claimed_child_ids: set = field(default_factory=set)
    last_status_line: Optional[str] = None
    model_ref: Optional[dict] = None


class Monitor:
    """Polls (SSE-nudged) session + message state and renders a live tree."""

    def __init__(self, client: OpenCodeClient, catalog: ModelCatalog, quiet: bool = False):
        self.client = client
        self.catalog = catalog
        self.quiet = quiet
        self.nodes: dict[str, SessionNode] = {}

    def run(self, root_session_id: str, root_agent_label: str, wait_timeout: float) -> str:
        self.nodes[root_session_id] = SessionNode(
            session_id=root_session_id, parent_id=None, depth=0, label=root_agent_label
        )

        waker = SSEWaker(self.client)
        waker.start()

        wait_error: list[Exception] = []
        wait_done = threading.Event()

        def _wait_target():
            try:
                self.client.wait(root_session_id, timeout=wait_timeout)
            except Exception as e:  # noqa: BLE001
                wait_error.append(e)
            finally:
                wait_done.set()

        wait_thread = threading.Thread(target=_wait_target, daemon=True)
        wait_thread.start()

        grace_passes_remaining = 2  # extra syncs after root goes idle, to catch trailing sub-agent output
        try:
            while True:
                woke_by_event = waker.wait(timeout=POLL_FALLBACK_INTERVAL)
                self._sync_all()
                if wait_done.is_set():
                    if grace_passes_remaining <= 0:
                        break
                    grace_passes_remaining -= 1
        finally:
            waker.stop()

        if wait_error:
            raise wait_error[0]

        return self._final_text(root_session_id)

    # -- syncing ----------------------------------------------------------

    def _sync_all(self) -> None:
        # iterate over a snapshot since _sync_node may add new nodes (children)
        for node in list(self.nodes.values()):
            self._sync_node(node)

    def _sync_node(self, node: SessionNode) -> None:
        try:
            info = self.client.get_session(node.session_id)
        except requests.exceptions.RequestException:
            return
        node.model_ref = info.get("model")

        if not self.quiet:
            self._maybe_print_status(node, info)

        try:
            messages = self.client.get_messages(node.session_id, order="asc")
        except requests.exceptions.RequestException:
            return

        for message in messages:
            self._handle_message(node, message)

    def _maybe_print_status(self, node: SessionNode, info: dict) -> None:
        tokens = info.get("tokens") or {}
        cost = info.get("cost")
        ctx_limit = self.catalog.context_limit(node.model_ref)
        ctx_used = tokens.get("input", 0) + (tokens.get("cache", {}) or {}).get("read", 0)
        pct = f"{(ctx_used / ctx_limit * 100):.1f}%" if ctx_limit else "?"
        line = (
            f"[{node.label}] tokens: {fmt_tokens(tokens)} | "
            f"context: {ctx_used}/{ctx_limit or '?'} ({pct}) | cost: ${cost or 0:.4f}"
        )
        if line != node.last_status_line:
            emit(node.depth, "\U0001F4CA", line)  # 📊
            node.last_status_line = line

    def _handle_message(self, node: SessionNode, message: dict) -> None:
        msg_id = message.get("id")
        msg_type = message.get("type")
        is_new = msg_id not in node.known_message_ids

        if msg_type == "assistant":
            self._handle_assistant_content(node, message)
            return  # assistant messages update incrementally; header not needed

        if not is_new:
            return
        node.known_message_ids.add(msg_id)

        if msg_type == "skill":
            emit(node.depth, "\U0001F4CE", f"skill activated: {message.get('name', message.get('skill'))}")
        elif msg_type == "agent-switched":
            emit(node.depth, "\U0001F501", f"agent switched -> {message.get('agent')}")
        elif msg_type == "model-switched":
            m = message.get("model", {})
            emit(node.depth, "\U0001F501", f"model switched -> {m.get('providerID')}/{m.get('id')}")
        elif msg_type == "user":
            text = (message.get("text") or "").strip()
            if text:
                preview = text if len(text) <= 300 else text[:300] + "…"
                emit(node.depth, "\U0001F464", f"user: {preview}")
        elif msg_type == "compaction":
            emit(node.depth, "\U0001F5DC", f"compaction {message.get('status')} ({message.get('reason')})")
        # "synthetic" / "system" messages are intentionally not printed (low signal)

    def _handle_assistant_content(self, node: SessionNode, message: dict) -> None:
        msg_id = message.get("id")
        node.known_message_ids.add(msg_id)
        content = message.get("content") or []

        for idx, part in enumerate(content):
            key = (msg_id, idx)
            ptype = part.get("type")

            if ptype == "text":
                self._render_growing_text(node, key, part.get("text", ""), icon="\U0001F4AC")  # 💬
            elif ptype == "reasoning":
                self._render_growing_text(node, key, part.get("text", ""), icon="\U0001F9E0")  # 🧠
            elif ptype == "tool":
                self._handle_tool_part(node, message, key, part)

    def _render_growing_text(self, node: SessionNode, key: tuple, text: str, icon: str) -> None:
        prev = node.part_state.get(key, {})
        prev_len = prev.get("len", 0)
        if len(text) <= prev_len:
            return
        delta = text[prev_len:][:TEXT_PREVIEW_CHARS]
        emit(node.depth, icon, delta)
        node.part_state[key] = {"len": len(text)}

    def _handle_tool_part(self, node: SessionNode, message: dict, key: tuple, part: dict) -> None:
        name = part.get("name", "?")
        state = part.get("state") or {}
        status = state.get("status")
        prev = node.part_state.get(key, {})

        if prev.get("status") == status:
            return  # no change to report
        node.part_state[key] = {**prev, "status": status}

        if status in ("streaming", "running"):
            tool_input = state.get("input")
            input_preview = _short_repr(tool_input)
            icon = "\U0001F916" if name == "task" else "\U0001F527"  # 🤖 for subagent, 🔧 otherwise
            emit(node.depth, icon, f"tool: {name} ({status}) input={input_preview}")
        elif status == "completed":
            output_preview = _short_repr(_tool_content_text(state.get("content")))
            emit(node.depth, "\u2705", f"tool: {name} completed -> {output_preview}")
        elif status == "error":
            err = (state.get("error") or {}).get("message", "unknown error")
            emit(node.depth, "\u274C", f"tool: {name} error -> {err}")

        if name == "task" and status in ("running", "completed") and key not in node.spawned_children:
            self._discover_child_session(node, key)

    def _discover_child_session(self, node: SessionNode, tool_key: tuple) -> None:
        node.spawned_children.add(tool_key)
        try:
            all_sessions = self.client.list_sessions()
        except requests.exceptions.RequestException:
            return
        candidates = [
            s for s in all_sessions
            if s.get("parentID") == node.session_id
            and s.get("id") not in self.nodes
            and s.get("id") not in node.claimed_child_ids
        ]
        if not candidates:
            return
        candidates.sort(key=lambda s: (s.get("time") or {}).get("created", 0))
        child = candidates[0]
        child_id = child["id"]
        node.claimed_child_ids.add(child_id)
        label = f"subagent:{child.get('agent', '?')}"
        self.nodes[child_id] = SessionNode(
            session_id=child_id, parent_id=node.session_id, depth=node.depth + 1, label=label
        )
        emit(node.depth, "\U0001F440", f"-> spawned child session {child_id} ({label})")

    def _final_text(self, session_id: str) -> str:
        try:
            messages = self.client.get_messages(session_id, order="desc", limit=20)
        except requests.exceptions.RequestException:
            return ""
        for message in messages:
            if message.get("type") == "assistant":
                parts = [
                    p.get("text", "") for p in (message.get("content") or []) if p.get("type") == "text"
                ]
                if parts:
                    return "\n".join(parts)
        return ""


def _short_repr(value: Any, limit: int = 200) -> str:
    text = value if isinstance(value, str) else str(value)
    text = text.replace("\n", " ")
    return text if len(text) <= limit else text[:limit] + "…"


def _tool_content_text(content: Any) -> str:
    if not isinstance(content, list):
        return ""
    parts = [c.get("text", "") for c in content if isinstance(c, dict) and c.get("type") == "text"]
    return " ".join(parts)


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Run a prompt on a local OpenCode server with live visibility")
    parser.add_argument("--base-url", default=os.environ.get("OPENCODE_URL", DEFAULT_BASE_URL),
                         help="Base URL of the running opencode server (default: http://localhost:4096)")
    parser.add_argument("--username", default=None,
                         help="Basic auth username (default: 'opencode', or $OPENCODE_SERVER_USERNAME)")
    parser.add_argument("--password", default=None,
                         help="Basic auth password (default: $OPENCODE_PASSWORD / $OPENCODE_SERVER_PASSWORD). "
                              "Required if the server was started without an explicit password, since opencode2 "
                              "then generates a random one and prints it to its own console at startup.")
    parser.add_argument("--directory", default=os.getcwd(),
                         help="Project directory the session should be scoped to (default: cwd)")
    parser.add_argument("--agent", required=True, help="Agent name to use for the session, e.g. 'build' or 'plan'")
    parser.add_argument("--skill", default=None, help="Skill name to activate before prompting (optional)")
    parser.add_argument("--provider", default=None, help="Provider ID to use, e.g. 'anthropic' (requires --model)")
    parser.add_argument("--model", default=None, help="Model ID to use, e.g. 'claude-sonnet-5' (requires --provider)")
    parser.add_argument("--variant", default=None, help="Optional model variant")
    parser.add_argument("--prompt", required=True, help="The prompt text to send")
    parser.add_argument("--title", default=None, help="Optional session title")
    parser.add_argument("--timeout", type=float, default=600.0, help="Max seconds to wait for a reply")
    parser.add_argument("--quiet", action="store_true", help="Suppress the live tree; print only the final answer")

    args = parser.parse_args()

    if bool(args.provider) != bool(args.model):
        parser.error("--provider and --model must be given together")

    return chat(args)


def chat(args) -> str:
    client = OpenCodeClient(args.base_url, username=args.username, password=args.password)

    try:
        client.health()
    except RuntimeError as e:  # our own 401 message
        print(str(e), file=sys.stderr)
        sys.exit(1)
    except requests.exceptions.RequestException as e:
        print(f"Could not reach OpenCode server at {args.base_url}: {e}", file=sys.stderr)
        sys.exit(1)

    model_note = f", model={args.provider}/{args.model}" if args.provider else ""
    if not args.quiet:
        print(f"Creating session (agent={args.agent}, directory={args.directory}{model_note})...")

    session_id = client.create_session(
        directory=args.directory,
        agent=args.agent,
        title=args.title,
        provider_id=args.provider,
        model_id=args.model,
        variant=args.variant,
    )
    if not args.quiet:
        print(f"Session created: {session_id}\n")

    if args.skill:
        client.activate_skill(session_id, args.skill, resume=False)

    client.send_prompt(session_id, args.prompt, resume=True)

    catalog = ModelCatalog(client)
    monitor = Monitor(client, catalog, quiet=args.quiet)
    reply = monitor.run(session_id, root_agent_label=f"root:{args.agent}", wait_timeout=args.timeout)

    print("\n--- Assistant reply ---\n" if not args.quiet else "", end="")
    print(reply if reply else "(no text content returned)")

    return reply

if __name__ == "__main__":
    main()